import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
export const dynamic='force-dynamic';
type Config={OPENAI_API_KEY?:string;AI_ENABLED?:string;OPENAI_IMAGE_MODEL?:string};
const config=()=>env as unknown as Config;
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function signature(id:string,user:string,key:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign']);const b=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(id+':'+user));return Array.from(new Uint8Array(b)).map(v=>v.toString(16).padStart(2,'0')).join('');}
async function provider(path:string,init:RequestInit={}){const r=await fetch('https://api.openai.com/v1/'+path,{...init,headers:{...init.headers,Authorization:'Bearer '+config().OPENAI_API_KEY},signal:AbortSignal.timeout(180000)});if(!r.ok){let code='';try{const e=await r.json() as {error?:{code?:string}};code=e.error?.code||'';}catch{}throw new Error(r.status===429?'이용 한도 또는 잔액을 확인해주세요.':r.status===401?'AI 연결 인증을 확인해주세요.':code.includes('moderation')?'이 요청은 생성 서비스에서 처리할 수 없습니다. 내용을 바꿔주세요.':'AI 서비스가 요청을 처리하지 못했습니다. 잠시 후 다시 시도해주세요.');}return r;}
export async function GET(req:Request){if(!await getChatGPTUser())return json({error:'로그인 후 이용해주세요.'},401);const url=new URL(req.url);if(!url.searchParams.has('id'))return json({image:!!config().OPENAI_API_KEY&&config().AI_ENABLED==='true',video:!!config().OPENAI_API_KEY&&config().AI_ENABLED==='true',instagram:false});try{const user=(await getChatGPTUser())!;const id=url.searchParams.get('id')!;if(!/^video_[a-zA-Z0-9_-]+$/.test(id)||!config().OPENAI_API_KEY)return json({error:'잘못된 영상 요청입니다.'},400);if(url.searchParams.get('token')!==await signature(id,user.userId,config().OPENAI_API_KEY!))return json({error:'이 영상에 접근할 수 없습니다.'},403);if(url.searchParams.get('download')==='1'){const r=await provider('videos/'+id+'/content');return new Response(r.body,{headers:{'Content-Type':'video/mp4','Cache-Control':'no-store','Content-Disposition':'attachment; filename="jini-voice.mp4"'}});}const r=await provider('videos/'+id);const d=await r.json() as {status:string;progress:number;error?:{message?:string}};return json({status:d.status,progress:d.progress,error:d.status==='failed'?'영상 생성에 실패했습니다. 제공 서비스의 생성 내역을 확인해주세요.':undefined});}catch(e){return json({error:e instanceof Error?e.message:'영상을 불러오지 못했습니다.'},502);}}
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return json({error:'로그인 후 이용해주세요.'},401);const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)return json({error:'잘못된 요청 경로입니다.'},403);if(!config().OPENAI_API_KEY||config().AI_ENABLED!=='true')return json({error:'AI 생성 서비스가 아직 연결되지 않았습니다. 현재는 내 사진으로 이미지·사진 영상을 만들 수 있습니다.',code:'NOT_CONFIGURED'},503);try{if(Number(req.headers.get('content-length')||0)>12*1024*1024)return json({error:'사진은 10MB 이하로 넣어주세요.'},413);const f=await req.formData();const prompt=f.get('prompt');const kind=f.get('kind');if(typeof prompt!=='string'||!prompt.trim()||prompt.length>2000||!['image','video'].includes(String(kind)))return json({error:'만들 내용을 1~2,000자로 입력해주세요.'},400);if(f.get('confirmed')!=='true')return json({error:'유료 생성 확인이 필요합니다.'},400);const photo=f.get('photo');if(photo instanceof File&&(photo.size>10*1024*1024||!['image/png','image/jpeg','image/webp'].includes(photo.type)))return json({error:'10MB 이하 JPG, PNG, WebP만 지원합니다.'},400);const ratio=f.get('ratio');if(kind==='image'){const size=ratio==='1:1'?'1024x1024':'1024x1536';const model=config().OPENAI_IMAGE_MODEL||'gpt-image-1.5';let r:Response;if(photo instanceof File&&photo.size){const body=new FormData();body.set('model',model);body.set('prompt',prompt+'\nCreate a social-media-ready background without text. Preserve the uploaded subject.');body.set('size',size);body.set('quality','medium');body.set('image',photo);r=await provider('images/edits',{method:'POST',body});}else r=await provider('images/generations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,prompt:prompt+'\nCreate a social-media-ready background without text.',size,quality:'medium',n:1})});const d=await r.json() as {data?:{b64_json?:string}[]};if(!d.data?.[0]?.b64_json)throw Error('생성 결과를 읽지 못했습니다.');return json({image:'data:image/png;base64,'+d.data[0].b64_json});}
 const body=new FormData();body.set('model','sora-2');body.set('prompt',prompt);body.set('size','720x1280');body.set('seconds','4');if(photo instanceof File&&photo.size)body.set('input_reference',photo);const r=await provider('videos',{method:'POST',body});const d=await r.json() as {id:string;status:string};return json({id:d.id,status:d.status,token:await signature(d.id,user.userId,config().OPENAI_API_KEY!)});
 }catch(e){return json({error:e instanceof Error?e.message:'AI 생성 중 오류가 발생했습니다.'},502);}}
