'use client';
import {useEffect,useRef,useState} from 'react';
import {AudioLines,Home,Search,Mic,Bell,User,Heart,MessageCircle,Bookmark,ArrowUpRight,Plus,RefreshCw,ArrowLeft,MoreHorizontal,Send,Settings,Check,X} from 'lucide-react';
import StoryComposer from '@/components/story-composer';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import '@/app/social.css';
type Profile={id:string;name:string;bio:string;emoji:string};
type Comment={id:string;user:string;body:string;created:number};
type Post={id:string;user:string;caption:string;created:number;media:{type:string;url:string}|null;likes:number;liked:boolean;comments:Comment[];ai?:boolean;sample?:boolean};
type Community={me:Profile;profiles:Profile[];posts:Post[];following:string[];followers:string[];blocked:{id:string;name:string}[];notifications:{type:string;user:string;post?:string;created:number;body?:string}[]};
const blank:Community={me:{id:'',name:'나의 프로필',emoji:'🙂',bio:''},profiles:[],posts:[],following:[],followers:[],blocked:[],notifications:[]};
const examples:Post[]=[{id:'sample-sea',user:'sample-walk',caption:'조금 천천히 걸었더니, 평소엔 못 보던 풍경이 보였어요. 🌊\n오늘 여러분의 작은 행복은 뭐였나요?',created:0,media:{type:'image/webp',url:'/visuals/quiet-sea.webp'},likes:0,liked:false,comments:[],sample:true},{id:'sample-text',user:'sample-day',caption:'엄마가 처음으로 음성 입력으로 안부를 보내주셨다.\n“밥은 먹었니?” 네 글자인데, 오늘 하루가 따뜻해졌다. 💛',created:0,media:null,likes:0,liked:false,comments:[],sample:true}];
const exampleProfiles:Profile[]=[{id:'sample-walk',name:'산책하는 하루',emoji:'🌊',bio:'산책과 풍경을 나누는 예시 프로필입니다.'},{id:'sample-day',name:'다정한 일상',emoji:'🌷',bio:'글로 나누는 일상 예시입니다.'}];
function ago(t:number){const mins=Math.max(0,Math.floor((Date.now()-t)/60000));return mins<1?'방금':mins<60?`${mins}분 전`:mins<1440?`${Math.floor(mins/60)}시간 전`:new Date(t).toLocaleDateString('ko-KR',{month:'long',day:'numeric'});}
export default function SocialApp(){
 const [view,setView]=useState('home'),[community,setCommunity]=useState<Community>(blank),[status,setStatus]=useState('loading'),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[dialog,setDialog]=useState(''),[code,setCode]=useState(''),[authError,setAuthError]=useState(''),[feedTab,setFeedTab]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Post|null>(null),[comment,setComment]=useState(''),[profile,setProfile]=useState<string|null>(null),[name,setName]=useState(''),[bio,setBio]=useState(''),[emoji,setEmoji]=useState('🙂'),[saved,setSaved]=useState<string[]>([]),[report,setReport]=useState(''),[composeKey,setComposeKey]=useState(0),[hasComposer,setHasComposer]=useState(false),[entryMode,setEntryMode]=useState<'voice'|'text'>('voice'),[seen,setSeen]=useState(0),[onlySaved,setOnlySaved]=useState(false);
 const pending=useRef(false),postingId=useRef<string|null>(null),commentId=useRef<string|null>(null);
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem('vg-saved')||'[]'));setSeen(Number(localStorage.getItem('vg-seen')||0));}catch{}void refresh();},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
 async function refresh(){try{const r=await fetch('/api/social');if(r.status===401){setStatus('locked');return;}if(!r.ok)throw Error();const d=await r.json() as Community;if(!Array.isArray(d.posts))throw Error();setCommunity(d);setStatus('ready');}catch{setStatus('error');}}
 function go(next:string){setView(next);setProfile(null);setOnlySaved(false);if(next==='create')setHasComposer(true);if(next==='notifications'){const now=Date.now();setSeen(now);try{localStorage.setItem('vg-seen',String(now));}catch{}}window.scrollTo({top:0,behavior:'instant'});}
 function start(mode:'voice'|'text'){setEntryMode(mode);go('create');}
 function requireLogin(){if(status!=='ready'){setDialog('login');return false;}return true;}
 async function action(body:Record<string,unknown>){if(!requireLogin()||pending.current)return false;pending.current=true;setBusy(true);try{const r=await fetch('/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as Community & {error?:string};if(!r.ok){if(r.status===401)setStatus('locked');throw Error(d.error||'요청을 완료하지 못했어요.');}setCommunity(d);return true;}catch(e){setToast(e instanceof Error?e.message:'연결을 확인해주세요.');return false;}finally{setBusy(false);pending.current=false;}}
 async function unlock(){if(pending.current)return;pending.current=true;setBusy(true);setAuthError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'unlock',code})});const d=await r.json() as Community & {error?:string};if(!r.ok)throw Error(d.error||'코드를 확인해주세요.');await refresh();window.dispatchEvent(new Event('voicegram-auth'));setCode('');setDialog('');setToast('테스트 공간에 연결했어요. 내 프로필에서 이름을 정해주세요.');}catch(e){setAuthError(e instanceof Error?e.message:'연결하지 못했어요.');}finally{pending.current=false;setBusy(false);}}
 async function publish(file:Blob|null,caption:string,ai:boolean){if(!requireLogin())throw Error('테스트 공간에 연결한 뒤 다시 게시해주세요.');if(pending.current)throw Error('앞선 요청이 끝나면 다시 시도해주세요.');pending.current=true;setBusy(true);postingId.current ||=crypto.randomUUID();try{const form=new FormData();form.set('id',postingId.current);form.set('caption',caption);form.set('ai',String(ai));if(file){let output=file;if(file.type.startsWith('image/')){const bmp=await createImageBitmap(file);const c=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(bmp.width,bmp.height));c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext('2d')!.drawImage(bmp,0,0,c.width,c.height);bmp.close();output=await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('사진을 준비하지 못했어요.')),'image/jpeg',.87));}if(output.size>4*1024*1024)throw Error('영상 파일이 4MB를 넘어요. 파일로 저장하거나 더 작은 파일을 이용해주세요.');form.set('file',output,'story');}const r=await fetch('/api/social',{method:'POST',body:form});const d=await r.json() as Community & {error?:string};if(!r.ok)throw Error(d.error||'게시하지 못했어요.');setCommunity(d);postingId.current=null;setComposeKey(v=>v+1);setHasComposer(false);setFeedTab('all');go('home');setToast('내 이야기를 피드에 올렸어요 ✨');}finally{pending.current=false;setBusy(false);}}
 const findProfile=(id:string)=>community.profiles.find(p=>p.id===id)||exampleProfiles.find(p=>p.id===id)||{id,name:'이웃',emoji:'🙂',bio:''};
 const openProfile=(id:string)=>{setProfile(id);setView('profile');setOnlySaved(false);window.scrollTo(0,0);};
 const activeProfile=profile?findProfile(profile):community.me;
 const myProfile=!profile||profile===community.me.id;
 const realPosts=community.posts;
 const homePosts=feedTab==='following'?realPosts.filter(p=>community.following.includes(p.user)):realPosts;
 const displayPosts=homePosts.length?homePosts:feedTab==='all'?examples:[];
 const searchPosts=realPosts.filter(p=>(p.caption+' '+findProfile(p.user).name).toLowerCase().includes(query.toLowerCase()));
 const profilePosts=onlySaved?realPosts.filter(p=>saved.includes(p.id)):realPosts.filter(p=>p.user===activeProfile.id);
 const unread=community.notifications.filter(n=>n.created>seen).length;
 const currentPost=selected?(community.posts.find(p=>p.id===selected.id)||selected):null;
 function toggleSaved(id:string){const next=saved.includes(id)?saved.filter(v=>v!==id):[...saved,id];setSaved(next);try{localStorage.setItem('vg-saved',JSON.stringify(next));}catch{setToast('이 기기에 저장하지 못했어요.');}}
 function postCard(p:Post){const author=findProfile(p.user);return <article className="feed-card" key={p.id} id={'post-'+p.id}>
 <header className="post-top"><button className="person-button" onClick={()=>openProfile(p.user)}><span className="social-avatar">{author.emoji}</span><span><strong>{author.name}</strong><small>{p.sample?'화면 체험용 예시':ago(p.created)}{p.ai?' · AI로 만든 이미지':''}</small></span></button>{!p.sample&&p.user!==community.me.id&&<button className="follow-mini" disabled={busy} onClick={()=>void action({action:'follow',id:p.user,value:!community.following.includes(p.user)})}>{community.following.includes(p.user)?'팔로잉':'팔로우'}</button>}{!p.sample&&<button className="icon-button" aria-label="게시물 메뉴" onClick={()=>{setSelected(p);setDialog('postmenu');}}><MoreHorizontal size={22}/></button>}</header>
 {p.media&&(p.media.type.startsWith('video')?<video className="feed-visual" src={p.media.url} controls playsInline preload="metadata"/>:<img className="feed-visual" src={p.media.url} alt={p.sample?'잔잔한 바다 위로 떠오르는 해':`${author.name}님의 게시물 사진`} loading="lazy"/>)}
 <div className={'post-body '+(!p.media?'text-post':'')}><p>{p.caption}</p></div>
 {p.sample?<><div className="post-actions sample-actions"><button disabled aria-label="예시 게시물 좋아요"><Heart size={24}/><span>좋아요</span></button><button disabled aria-label="예시 게시물 댓글"><MessageCircle size={24}/><span>댓글</span></button><button disabled className="save-post" aria-label="예시 게시물 저장"><Bookmark size={23}/></button></div><div className="sample-footer"><span>예시 게시물 · 실제 사용자 글이 아니에요</span><button onClick={()=>go('create')}>내 이야기 올리기 <ArrowUpRight size={16}/></button></div></>:<><div className="post-actions"><button aria-label={p.liked?'좋아요 취소':'좋아요'} aria-pressed={p.liked} className={p.liked?'liked':''} disabled={busy} onClick={()=>void action({action:'like',id:p.id,value:!p.liked})}><Heart size={24} fill={p.liked?'currentColor':'none'}/><span>{p.likes||'좋아요'}</span></button><button aria-label="댓글 열기" onClick={()=>{setSelected(p);setComment('');setDialog('comments');}}><MessageCircle size={24}/><span>{p.comments.length||'댓글'}</span></button><button className="save-post" aria-label={saved.includes(p.id)?'저장 취소':'게시물 저장'} aria-pressed={saved.includes(p.id)} onClick={()=>toggleSaved(p.id)}><Bookmark size={23} fill={saved.includes(p.id)?'currentColor':'none'}/></button></div>{p.comments.length>0&&<button className="comment-peek" onClick={()=>{setSelected(p);setDialog('comments');}}><strong>{findProfile(p.comments[p.comments.length-1].user).name}</strong> {p.comments[p.comments.length-1].body}</button>}</>}
 </article>;}
 const nav=[{id:'home',label:'홈',icon:Home},{id:'explore',label:'둘러보기',icon:Search},{id:'create',label:'만들기',icon:Mic},{id:'notifications',label:'알림',icon:Bell},{id:'profile',label:'내 프로필',icon:User}];
 return <div className="social-app"><aside className="social-sidebar"><button className="social-logo" onClick={()=>go('home')}><span><AudioLines size={27}/></span>보이스그램</button><p className="brand-tagline">말로 나누는, 우리 일상</p><nav aria-label="주 메뉴">{nav.map(({id,label,icon:Icon})=><button key={id} className={(view===id?'active ':'')+(id==='create'?'nav-create':'')} aria-current={view===id?'page':undefined} onClick={()=>go(id)}><Icon size={24}/>{label}{id==='notifications'&&unread>0&&<i className="unread-dot"/>}</button>)}</nav><div className="sidebar-bottom"><button className="person-button" onClick={()=>go('profile')}><span className="social-avatar">{community.me.emoji}</span><span><strong>{community.me.name}</strong><small>{status==='ready'?'테스트 프로필':'둘러보는 중'}</small></span></button><button className="settings-link" onClick={()=>setDialog('settings')}><Settings size={17}/>설정 및 이용 안내</button></div></aside>
 <main className="social-main"><header className="social-topbar"><button className="social-logo" onClick={()=>go('home')}><span><AudioLines size={23}/></span>보이스그램</button><span className="desktop-title">{view==='home'?'우리의 이야기':view==='explore'?'새로운 일상 발견':view==='create'?'내 이야기 만들기':view==='notifications'?'나에게 온 소식':'프로필'}</span><button className="icon-button" aria-label="설정" onClick={()=>setDialog('settings')}><Settings size={22}/></button></header>
 <div className="social-columns"><div className="social-center">
 {view==='home'&&<><div className="feed-heading"><div><h1>안녕, 오늘은 어땠어요?</h1><p>서로의 하루를 듣고, 내 이야기도 나눠요.</p></div><span aria-hidden="true">👋</span></div><div className="quick-create"><button onClick={()=>start('voice')}><span className="start-mic"><Mic size={26}/></span><span><strong>말로 만들기</strong><small>편하게 이야기해요</small></span></button><button onClick={()=>start('text')}><span className="write-symbol">✏️</span><span><strong>글로 쓰기</strong><small>직접 적어볼게요</small></span></button></div><div className="feed-tabs"><div><button className={feedTab==='all'?'on':''} aria-pressed={feedTab==='all'} onClick={()=>setFeedTab('all')}>전체 피드</button><button className={feedTab==='following'?'on':''} aria-pressed={feedTab==='following'} onClick={()=>setFeedTab('following')}>팔로잉</button></div><button className="icon-button" aria-label="피드 새로고침" onClick={()=>void refresh()}><RefreshCw size={19}/></button></div>{status==='loading'&&<p className="inline-status" role="status">이야기를 불러오는 중…</p>}{status==='locked'&&<div className="connection-banner"><p>지금은 예시 피드를 보고 있어요.</p><button onClick={()=>setDialog('login')}>테스트 참여하기</button></div>}{status==='error'&&<div className="connection-banner"><p>피드를 불러오지 못했어요. 아래는 예시입니다.</p><button onClick={()=>void refresh()}>다시 연결</button></div>}{status==='ready'&&realPosts.length===0&&<div className="connection-banner"><p>아직 게시물이 없어요. 첫 이야기를 남겨주세요.</p></div>}{displayPosts.map(postCard)}{!displayPosts.length&&<div className="social-empty"><span>🌱</span><h2>팔로우한 이웃의 이야기가 모여요</h2><p>전체 피드나 둘러보기에서 마음이 맞는 이웃을 찾아보세요.</p><button className="primary" onClick={()=>go('explore')}>이웃 둘러보기</button></div>}</>}
 {view==='explore'&&<><div className="page-heading"><h1>둘러보기</h1><p>궁금한 이야기와 새로운 이웃을 찾아요.</p></div><label className="social-search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="이야기, 이름, #관심사 검색" aria-label="게시물과 프로필 검색"/></label><div className="interest-chips">{['전체','일상','여행','반려동물','오늘'].map(t=><button key={t} aria-pressed={query===(t==='전체'?'':t)} onClick={()=>setQuery(t==='전체'?'':t)}>{t==='일상'?'☕ ':t==='여행'?'🌊 ':t==='반려동물'?'🐾 ':''}{t}</button>)}</div><h2 className="list-heading">함께 이야기할 이웃</h2>{community.profiles.filter(p=>p.id!==community.me.id&&(p.name+p.bio).includes(query)).map(p=><div className="neighbor-row" key={p.id}><button className="person-button" onClick={()=>openProfile(p.id)}><span className="social-avatar">{p.emoji}</span><span><strong>{p.name}</strong><small>{p.bio||'새로운 이웃이에요'}</small></span></button><button className="follow-mini" disabled={busy} onClick={()=>void action({action:'follow',id:p.id,value:!community.following.includes(p.id)})}>{community.following.includes(p.id)?'팔로잉':'팔로우'}</button></div>)}{community.profiles.filter(p=>p.id!==community.me.id).length===0&&<p className="empty-inline">참여한 이웃이 생기면 여기에서 만날 수 있어요.</p>}<h2 className="list-heading">이야기</h2>{searchPosts.map(postCard)}{searchPosts.length===0&&<div className="social-empty"><span>🔎</span><h2>{query?'아직 이 이야기는 없어요':'첫 이야기를 기다리고 있어요'}</h2><p>함께 나누고 싶은 순간을 먼저 올려보세요.</p><button className="primary" onClick={()=>go('create')}>내 이야기 만들기</button></div>}</>}
 {hasComposer&&<div hidden={view!=='create'}><StoryComposer key={composeKey} active={view==='create'} entryMode={entryMode} onPublish={publish} onClose={()=>go('home')}/></div>}
 {view==='notifications'&&<><div className="page-heading"><h1>알림</h1><p>내 이야기에 도착한 마음들</p></div>{community.notifications.length?community.notifications.map((n,i)=><button className="notification-row" key={n.type+n.user+n.created+i} onClick={()=>{if(n.type==='follow')openProfile(n.user);else{const p=community.posts.find(p=>p.id===n.post);if(p){setSelected(p);setDialog('comments');}}}}><span className="social-avatar">{findProfile(n.user).emoji}</span><span><strong>{findProfile(n.user).name}</strong>님이 {n.type==='like'?'내 이야기를 좋아해요.':n.type==='comment'?'댓글을 남겼어요.':'나를 팔로우했어요.'}{n.body&&<em>{n.body}</em>}<small>{ago(n.created)}</small></span></button>):<div className="social-empty"><span>💌</span><h2>새로운 소식을 기다리고 있어요</h2><p>좋아요, 댓글, 팔로우가 생기면 알려드려요.<br/>앱을 열어 새로고침하면 확인할 수 있어요.</p></div>}<button className="secondary" onClick={()=>void refresh()}>새 소식 확인</button></>}
 {view==='profile'&&<><div className="profile-cover"><span>나답게 말하고, 함께 나누는 곳.</span><span aria-hidden="true">✦</span></div><section className="profile-info"><span className="profile-avatar">{activeProfile.emoji}</span><div className="profile-title"><h1>{activeProfile.name}</h1>{myProfile?<button className="profile-edit" onClick={()=>{if(!requireLogin())return;setName(community.me.name);setBio(community.me.bio);setEmoji(community.me.emoji);setDialog('edit');}}>프로필 편집</button>:!activeProfile.id.startsWith('sample')&&<button className="profile-edit" onClick={()=>void action({action:'follow',id:activeProfile.id,value:!community.following.includes(activeProfile.id)})}>{community.following.includes(activeProfile.id)?'팔로잉':'팔로우'}</button>}</div><p>{activeProfile.bio||'나의 하루를 이야기로 남겨보세요.'}</p><div className="profile-counts"><span><b>{realPosts.filter(p=>p.user===activeProfile.id).length}</b> 게시물</span>{myProfile&&<><span><b>{community.followers.length}</b> 팔로워</span><span><b>{community.following.length}</b> 팔로잉</span></>}</div>{myProfile&&<p className="profile-beta">테스트용 기기 프로필 · 다른 기기와 계정이 연동되지 않아요.</p>}</section>{myProfile&&<div className="quick-create profile-create"><button onClick={()=>start('voice')}><span className="start-mic"><Mic size={24}/></span><span><strong>말로 만들기</strong></span></button><button onClick={()=>start('text')}><span className="write-symbol">✏️</span><span><strong>글로 쓰기</strong></span></button></div>}<div className="feed-tabs"><div><button className={!onlySaved?'on':''} onClick={()=>setOnlySaved(false)}>게시물</button>{myProfile&&<button className={onlySaved?'on':''} onClick={()=>setOnlySaved(true)}>저장한 글</button>}</div></div>{onlySaved&&<p className="muted">저장 목록은 이 기기에 보관됩니다.</p>}{profilePosts.map(postCard)}{profilePosts.length===0&&<div className="social-empty"><span>{onlySaved?'🔖':'📷'}</span><h2>{onlySaved?'마음에 드는 이야기를 저장해보세요':'아직 이야기가 없어요'}</h2>{myProfile&&!onlySaved&&<button className="primary" onClick={()=>go('create')}>첫 이야기 올리기</button>}</div>}</>}
 </div><aside className="social-right"><div className="right-welcome"><img src="/visuals/voicegram-world.webp" alt="말풍선과 사진으로 표현한 보이스그램"/><h2>말 한마디로,<br/>더 가까워지는 우리.</h2><p>사진이 없어도, 멋진 글이 아니어도.<br/>당신의 이야기가 궁금해요.</p><button onClick={()=>go('create')}>내 이야기 나누기 <ArrowUpRight size={17}/></button></div><div className="right-how"><h3>이렇게 시작해요</h3><p><b>1</b>말하거나 글로 이야기해요</p><p><b>2</b>AI와 다듬고 미리 봐요</p><p><b>3</b>피드에 올리고 소통해요</p></div><p className="right-foot">보이스그램 · JINI TEAM<br/><button onClick={()=>setDialog('settings')}>테스트 안내 · 개인정보</button></p></aside></div></main>
 <nav className="bottom-nav" aria-label="모바일 주 메뉴">{nav.map(({id,label,icon:Icon})=><button key={id} className={(view===id?'active ':'')+(id==='create'?'center-create':'')} aria-current={view===id?'page':undefined} onClick={()=>go(id)}><span><Icon size={id==='create'?25:23}/>{id==='notifications'&&unread>0&&<i className="unread-dot"/>}</span><small>{label}</small></button>)}</nav>
 {toast&&<div className="social-toast" role="status">{toast}</div>}
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v){setDialog('');setAuthError('');}}}><DialogContent className="social-dialog"><DialogTitle>{dialog==='login'?'테스트 공간 참여':dialog==='comments'?'이야기 나누기':dialog==='edit'?'내 프로필 꾸미기':dialog==='report'?'게시물 신고':dialog==='postmenu'?'게시물 메뉴':dialog==='delete'?'게시물을 삭제할까요?':'설정 및 이용 안내'}</DialogTitle><DialogDescription>{dialog==='login'?'초대받은 테스트 접근 코드를 입력해주세요.':dialog==='comments'?'다정한 한마디를 남겨주세요.':dialog==='edit'?'이웃들에게 보여줄 나를 소개해요.':dialog==='delete'?'삭제하면 피드에서 사라집니다. 되돌릴 수 없어요.':dialog==='report'?'신고 사유를 기록합니다. 자동 처리되지는 않습니다.':'보이스그램 테스트 공간'}</DialogDescription>
 {dialog==='login'&&<><p className="muted">게시물과 프로필은 참여한 테스터에게 공개됩니다. 기기 쿠키가 프로필을 구분하므로 쿠키를 지우면 내 프로필을 다시 관리할 수 없어요. 정식 회원 로그인은 아직 준비 중입니다.</p><input type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} aria-label="테스트 접근 코드" placeholder="테스트 접근 코드"/><button className="primary" onClick={unlock} disabled={busy||!code}>{busy?'연결 중…':'참여하기'}</button>{authError&&<p role="alert">{authError}</p>}</>}
 {dialog==='edit'&&<><div className="avatar-choices">{['🙂','🌊','🌷','🐶','☕','🌳','🌙','🦋'].map(e=><button key={e} aria-label={e+' 프로필'} aria-pressed={e===emoji} onClick={()=>setEmoji(e)}>{e}</button>)}</div><label htmlFor="profile-name">이름</label><input id="profile-name" value={name} onChange={e=>setName(e.target.value)} maxLength={24}/><label htmlFor="profile-bio">한 줄 소개</label><textarea id="profile-bio" value={bio} onChange={e=>setBio(e.target.value)} maxLength={100} rows={2}/><button className="primary" disabled={busy||!name.trim()} onClick={async()=>{if(await action({action:'profile',name,bio,emoji})){setDialog('');setToast('프로필을 바꿨어요.');}}}>저장</button></>}
 {dialog==='comments'&&currentPost&&<><div className="comment-original">{currentPost.caption}</div><div className="comment-list">{currentPost.comments.length?currentPost.comments.map(c=><div className="comment-row" key={c.id}><span className="social-avatar">{findProfile(c.user).emoji}</span><div><strong>{findProfile(c.user).name}</strong><p>{c.body}</p><small>{ago(c.created)}</small></div>{c.user===community.me.id&&<button className="icon-button" aria-label="내 댓글 삭제" disabled={busy} onClick={()=>void action({action:'deleteComment',id:c.id})}><X size={17}/></button>}</div>):<p className="empty-inline">첫 댓글로 마음을 전해보세요.</p>}</div><form className="comment-form" onSubmit={async e=>{e.preventDefault();commentId.current ||=crypto.randomUUID();if(await action({action:'comment',id:currentPost.id,body:comment,requestId:commentId.current})){setComment('');commentId.current=null;}}}><input value={comment} onChange={e=>{setComment(e.target.value);commentId.current=null;}} aria-label="댓글" maxLength={500} placeholder="따뜻한 한마디…"/><button className="icon-button" disabled={busy||!comment.trim()} aria-label="댓글 보내기"><Send size={21}/></button></form></>}
 {dialog==='postmenu'&&currentPost&&<>{currentPost.user===community.me.id?<button className="menu-action danger" onClick={()=>setDialog('delete')}>내 게시물 삭제</button>:<><button className="menu-action" onClick={()=>{setReport('');setDialog('report');}}>신고하기</button><button className="menu-action" disabled={busy} onClick={async()=>{if(await action({action:'block',id:currentPost.user,value:true})){setDialog('');setToast('이 사용자의 게시물과 댓글을 숨겼어요. 설정에서 해제할 수 있어요.');}}}>이 사용자 차단</button></>}</>}
 {dialog==='delete'&&currentPost&&<><button className="primary" disabled={busy} onClick={async()=>{if(await action({action:'delete',id:currentPost.id})){setDialog('');setToast('게시물을 삭제했어요.');}}}>삭제하기</button><button className="secondary" onClick={()=>setDialog('')}>취소</button></>}
 {dialog==='report'&&currentPost&&<><textarea aria-label="신고 사유" value={report} onChange={e=>setReport(e.target.value)} maxLength={500} rows={3}/><button className="primary" disabled={busy||!report.trim()} onClick={async()=>{if(await action({action:'report',id:currentPost.id,reason:report})){setDialog('');setToast('신고를 기록했어요. 바로 숨기려면 사용자 차단을 이용해주세요.');}}}>신고 기록하기</button></>}
 {dialog==='settings'&&<div className="settings-content"><h3>현재 연결</h3><p>{status==='ready'?'테스트 공간 연결됨':'테스트 공간 연결 전'}</p>{status!=='ready'&&<button className="primary" onClick={()=>setDialog('login')}>테스트 공간 참여하기</button>}<h3>내 정보와 게시물</h3><p>게시물·댓글·프로필·좋아요·팔로우는 서버에 저장되며 테스터가 볼 수 있어요. 임시 작성글과 저장 목록은 이 기기에 보관됩니다. 테스트 프로필은 기기 쿠키에 연결되어 있으며, 정식 가입·계정 복구는 준비 중입니다.</p><h3>말로 만들기</h3><p>마이크 권한이 필요하고 브라우저에 따라 음성 입력 지원이 달라요. 음성은 브라우저의 인식 서비스에 전달될 수 있습니다. AI 다듬기를 사용하면 대화와 문구가 OpenAI에 전달되고 API 사용료가 발생합니다. 이동 중에는 안전하게 멈춘 뒤 확인하고 게시해주세요.</p><h3>차단한 사용자</h3>{community.blocked.length?community.blocked.map(b=><div className="neighbor-row" key={b.id}><span>{b.name}</span><button className="text-button" disabled={busy} onClick={()=>void action({action:'block',id:b.id,value:false})}>차단 해제</button></div>):<p>차단한 사용자가 없어요.</p>}<p className="muted">인스타그램 연결은 보류 중입니다. 이 피드는 보이스그램 안에서 나누는 이야기예요. 정식 공개 전 회원 인증·신고 처리·운영 정책을 갖출 예정입니다.</p></div>}
 </DialogContent></Dialog></div>;
}
