'use client';
import {lazy,Suspense,useEffect,useLayoutEffect,useRef,useState} from 'react';
import {AudioLines,Home,Search,Mic,Bell,User,ArrowUpRight,RefreshCw,Send,Settings,Check,X,Grid2X2,Rows3,Film,Type,Image as ImageIcon,Shuffle} from 'lucide-react';
import {storyPrompts} from '@/lib/story-prompts';
import FeedPost from '@/components/feed-post';
import SocialMedia from '@/components/social-media';
import FeatureBoundary from '@/components/feature-boundary';
import type {Profile,Post,Community} from '@/lib/social-types';
const BillingPanel=lazy(()=>import('@/components/billing-panel'));
const StoryComposer=lazy(()=>import('@/components/story-composer'));
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import '@/app/social.css';
const blank:Community={me:{id:'',name:'나의 프로필',emoji:'🙂',bio:''},profiles:[],posts:[],following:[],followers:[],blocked:[],notifications:[]};
const examples:Post[]=[{id:'sample-sea',user:'sample-walk',caption:'조금 천천히 걸었더니, 평소엔 못 보던 풍경이 보였어요. 🌊\n오늘 여러분의 작은 행복은 뭐였나요?',created:0,media:{type:'image/webp',url:'/visuals/quiet-sea.webp'},likes:0,liked:false,comments:[],sample:true},{id:'sample-text',user:'sample-day',caption:'엄마가 처음으로 음성 입력으로 안부를 보내주셨다.\n“밥은 먹었니?” 네 글자인데, 오늘 하루가 따뜻해졌다. 💛',created:0,media:null,likes:0,liked:false,comments:[],sample:true}];
const exampleProfiles:Profile[]=[{id:'sample-walk',name:'산책하는 하루',emoji:'🌊',bio:'산책과 풍경을 나누는 예시 프로필입니다.'},{id:'sample-day',name:'다정한 일상',emoji:'🌷',bio:'글로 나누는 일상 예시입니다.'}];
function ago(t:number){const mins=Math.max(0,Math.floor((Date.now()-t)/60000));return mins<1?'방금':mins<60?`${mins}분 전`:mins<1440?`${Math.floor(mins/60)}시간 전`:new Date(t).toLocaleDateString('ko-KR',{month:'long',day:'numeric'});}
export default function SocialApp(){
 const [auth,setAuth]=useState<{kakaoReady:boolean;authenticated:boolean;provider:string|null;checked:boolean}>({kakaoReady:false,authenticated:false,provider:null,checked:false});
 const [loginBusy,setLoginBusy]=useState(false);
 const [view,setView]=useState('home'),[community,setCommunity]=useState<Community>(blank),[status,setStatus]=useState('loading'),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[dialog,setDialog]=useState(''),[code,setCode]=useState(''),[authError,setAuthError]=useState(''),[feedTab,setFeedTab]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Post|null>(null),[comment,setComment]=useState(''),[profile,setProfile]=useState<string|null>(null),[name,setName]=useState(''),[bio,setBio]=useState(''),[emoji,setEmoji]=useState('🙂'),[saved,setSaved]=useState<string[]>([]),[report,setReport]=useState(''),[composeKey,setComposeKey]=useState(0),[hasComposer,setHasComposer]=useState(false),[entryMode,setEntryMode]=useState<'voice'|'text'>('voice'),[seen,setSeen]=useState(0),[onlySaved,setOnlySaved]=useState(false);
 const [exploreTab,setExploreTab]=useState('stories'),[mediaFilter,setMediaFilter]=useState('all'),[layout,setLayout]=useState('grid'),[promptIndex,setPromptIndex]=useState(0),[starter,setStarter]=useState<{id:number;question:string}|null>(null),[largeText,setLargeText]=useState(false),[speaking,setSpeaking]=useState('');
 const speechId=useRef('');
 const [refreshing,setRefreshing]=useState(false),[feedLimit,setFeedLimit]=useState(12),[shareUrl,setShareUrl]=useState('');
 const refreshTask=useRef<Promise<void>|null>(null),revision=useRef(0),homeScroll=useRef(0),restoreHome=useRef(false),pendingLink=useRef('');
 useLayoutEffect(()=>{window.scrollTo({top:view==='home'&&restoreHome.current?homeScroll.current:0,behavior:'instant'});restoreHome.current=false;},[view,profile]);
 useEffect(()=>{const q=new URLSearchParams(location.search);let id=q.get('post');try{if(!id&&q.get('auth')==='success')id=sessionStorage.getItem('vg-auth-post');}catch{}if(id&&/^[a-f0-9-]{36}$/.test(id))pendingLink.current=id;},[]);
 useEffect(()=>{if(status!=='ready'||!pendingLink.current)return;const id=pendingLink.current;pendingLink.current='';try{sessionStorage.removeItem('vg-auth-post');}catch{}const p=community.posts.find(p=>p.id===id);if(p){setSelected(p);setDialog('detail');}else setToast('삭제되었거나 볼 수 없는 게시물이에요.');const u=new URL(location.href);u.searchParams.delete('post');history.replaceState(null,'',u.pathname+u.search+u.hash);},[status,community]);

 useEffect(()=>{try{setLargeText(localStorage.getItem('vg-large-text')==='true');}catch{}return()=>{if(speechId.current)window.speechSynthesis?.cancel();};},[]);
 useEffect(()=>{if(speechId.current){speechId.current='';window.speechSynthesis?.cancel();setSpeaking('');}},[view,dialog]);
 function readPost(p:Post){if(!('speechSynthesis' in window)){setToast('이 브라우저는 읽어주기를 지원하지 않아요.');return;}const stop=speechId.current===p.id;speechId.current='';window.speechSynthesis.cancel();setSpeaking('');if(stop)return;const utterance=new SpeechSynthesisUtterance(p.caption);utterance.lang='ko-KR';utterance.rate=.95;utterance.onend=()=>{if(speechId.current===p.id){speechId.current='';setSpeaking('');}};utterance.onerror=()=>{if(speechId.current===p.id){speechId.current='';setSpeaking('');setToast('소리를 재생하지 못했어요. 기기의 음성 설정을 확인해주세요.');}};speechId.current=p.id;setSpeaking(p.id);window.speechSynthesis.speak(utterance);}
 const pending=useRef(false),postingId=useRef<string|null>(null),commentId=useRef<string|null>(null);
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem('vg-saved')||'[]'));setSeen(Number(localStorage.getItem('vg-seen')||0));}catch{}void refresh();void refreshAuth();const q=new URLSearchParams(location.search);if(q.has('payment')){setView('billing');}else if(q.has('auth')){const result=q.get('auth');history.replaceState(null,'',location.pathname);if(result!=='success'){setToast(result==='cancelled'?'로그인을 취소했어요. 작성하던 내용은 남아 있어요.':result==='expired'?'로그인 시간이 지났어요. 다시 시작해주세요.':'카카오 로그인을 완료하지 못했어요. 다시 시도해주세요.');}let resume='home';try{resume=sessionStorage.getItem('vg-auth-resume')||'home';sessionStorage.removeItem('vg-auth-resume');}catch{}if(['home','profile','create','billing'].includes(resume))go(resume);}},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
 async function refreshAuth(){try{const r=await fetch('/api/auth');if(!r.ok)throw Error();const d=await r.json() as {kakaoReady:boolean;authenticated:boolean;provider:string|null};setAuth({...d,checked:true});}catch{setAuth(v=>({...v,checked:true}));}}
 async function kakaoLogin(){if(loginBusy||!auth.kakaoReady)return;setLoginBusy(true);setAuthError('');try{window.dispatchEvent(new Event('voicegram-before-login'));try{sessionStorage.setItem('vg-auth-resume',view);if(pendingLink.current)sessionStorage.setItem('vg-auth-post',pendingLink.current);else sessionStorage.removeItem('vg-auth-post');}catch{}const r=await fetch('/api/auth?action=start',{method:'POST'});const d=await r.json() as {authorizeUrl?:string;error?:string};if(!r.ok||!d.authorizeUrl)throw Error(d.error||'로그인을 시작하지 못했어요.');const u=new URL(d.authorizeUrl);if(u.origin!=='https://kauth.kakao.com')throw Error('로그인 주소를 확인하지 못했어요.');location.assign(u.href);}catch(e){setAuthError(e instanceof Error?e.message:'연결을 확인해주세요.');setLoginBusy(false);}}
 async function logout(){if(busy)return;setBusy(true);revision.current++;try{const r=await fetch('/api/auth?action=logout',{method:'POST'});if(!r.ok)throw Error();setCommunity(blank);setStatus('locked');setHasComposer(false);setComposeKey(v=>v+1);setDialog('');go('home');await refreshAuth();window.dispatchEvent(new Event('voicegram-auth'));setToast('이 기기에서 로그아웃했어요.');}catch{setToast('로그아웃하지 못했어요. 다시 시도해주세요.');}finally{setBusy(false);}}
 function refresh(){if(refreshTask.current)return refreshTask.current;if(pending.current)return Promise.resolve();const version=revision.current;setRefreshing(true);const task=(async()=>{try{const r=await fetch('/api/social');if(version!==revision.current)return;if(r.status===401){setCommunity(blank);setStatus('locked');return;}if(!r.ok)throw Error();const d=await r.json() as Community;if(!Array.isArray(d.posts))throw Error();if(version!==revision.current)return;setCommunity(d);setStatus('ready');}catch{if(version===revision.current)setStatus('error');}finally{setRefreshing(false);refreshTask.current=null;}})();refreshTask.current=task;return task;}
 function go(next:string){if(view==='home'&&next!=='home')homeScroll.current=window.scrollY;restoreHome.current=next==='home'&&view!=='home';if(next==='home'&&view==='home')window.scrollTo({top:0,behavior:'smooth'});setView(next);setProfile(null);setOnlySaved(false);if(next==='create')setHasComposer(true);if(next==='notifications'){const now=Date.now();setSeen(now);try{localStorage.setItem('vg-seen',String(now));}catch{}}}
 function start(mode:'voice'|'text',question?:string){setEntryMode(mode);if(question)setStarter({id:Date.now(),question});go('create');}
 function requireLogin(){if(status!=='ready'){setDialog('login');return false;}return true;}
 async function action(body:Record<string,unknown>){if(!requireLogin()||pending.current)return false;pending.current=true;setBusy(true);revision.current++;const prior=body.action==='like'?community.posts.find(p=>p.id===body.id):undefined;if(prior){setCommunity(c=>({...c,posts:c.posts.map(p=>p.id===prior.id?{...p,liked:body.value===true,likes:Math.max(0,p.likes+(body.value===true?1:-1))}:p)}));}try{const r=await fetch('/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as Community & {error?:string};if(!r.ok){if(r.status===401){setCommunity(blank);setStatus('locked');}throw Error(d.error||'요청을 완료하지 못했어요.');}setCommunity(d);setStatus('ready');return true;}catch(e){if(prior)setCommunity(c=>({...c,posts:c.posts.map(p=>p.id===prior.id?{...p,liked:prior.liked,likes:prior.likes}:p)}));setToast(e instanceof Error?e.message:'연결을 확인해주세요.');return false;}finally{revision.current++;setBusy(false);pending.current=false;}}
 async function sharePost(p:Post){const url=new URL('/',location.origin);url.searchParams.set('post',p.id);if(navigator.share){try{await navigator.share({title:'보이스그램 · '+findProfile(p.user).name,text:p.caption.slice(0,100),url:url.href});return;}catch(e){if(e instanceof Error&&e.name==='AbortError')return;}}setShareUrl(url.href);setDialog('share');}
 async function copyShare(){try{await navigator.clipboard.writeText(shareUrl);setToast('게시물 링크를 복사했어요.');}catch{setToast('아래 링크를 길게 눌러 복사해주세요.');}}
 async function unlock(){if(pending.current)return;revision.current++;window.dispatchEvent(new Event('voicegram-before-login'));pending.current=true;setBusy(true);setAuthError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'unlock',code})});const d=await r.json() as Community & {error?:string};if(!r.ok)throw Error(d.error||'코드를 확인해주세요.');pending.current=false;await refreshTask.current;await refresh();window.dispatchEvent(new Event('voicegram-auth'));setCode('');setDialog('');setToast('테스트 공간에 연결했어요. 내 프로필에서 이름을 정해주세요.');}catch(e){setAuthError(e instanceof Error?e.message:'연결하지 못했어요.');}finally{pending.current=false;setBusy(false);}}
 async function publish(file:Blob|null,caption:string,ai:boolean,id?:string,videoJob?:{id:string;token:string}){if(!requireLogin())throw Error('로그인한 뒤 다시 게시해주세요.');if(pending.current)throw Error('앞선 요청이 끝나면 다시 시도해주세요.');pending.current=true;setBusy(true);revision.current++;postingId.current =id||postingId.current||crypto.randomUUID();try{const form=new FormData();form.set('id',postingId.current);form.set('caption',caption);form.set('ai',String(ai));if(videoJob){form.set('videoJob',videoJob.id);form.set('videoToken',videoJob.token);}if(file&&!videoJob){let output=file;if(file.type.startsWith('image/')){const bmp=await createImageBitmap(file);const c=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(bmp.width,bmp.height));c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext('2d')!.drawImage(bmp,0,0,c.width,c.height);bmp.close();output=await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('사진을 준비하지 못했어요.')),'image/jpeg',.87));}if(output.size>4*1024*1024)throw Error('영상 파일이 4MB를 넘어요. 파일로 저장하거나 더 작은 파일을 이용해주세요.');form.set('file',output,'story');}const r=await fetch('/api/social',{method:'POST',body:form});const d=await r.json() as Community & {error?:string};if(!r.ok)throw Error(d.error||'게시하지 못했어요.');setCommunity(d);postingId.current=null;setComposeKey(v=>v+1);setHasComposer(false);setFeedTab('all');setFeedLimit(12);homeScroll.current=0;go('home');setToast('내 이야기를 피드에 올렸어요 ✨');}finally{pending.current=false;setBusy(false);}}
 const findProfile=(id:string)=>community.profiles.find(p=>p.id===id)||exampleProfiles.find(p=>p.id===id)||{id,name:'이웃',emoji:'🙂',bio:''};
 const openProfile=(id:string)=>{if(view==='home')homeScroll.current=window.scrollY;setDialog('');setProfile(id);setView('profile');setOnlySaved(false);window.scrollTo(0,0);};
 const activeProfile=profile?findProfile(profile):community.me;
 const myProfile=!profile||profile===community.me.id;
 const realPosts=community.posts;
 const homePosts=feedTab==='following'?realPosts.filter(p=>community.following.includes(p.user)):realPosts;
 const displayPosts=homePosts.length?homePosts:feedTab==='all'&&status!=='loading'?examples:[];
 const searchTerm=query.trim().toLocaleLowerCase();
 const explorePool=realPosts.length?realPosts:examples;
 const searchPosts=explorePool.filter(p=>(p.caption+' '+findProfile(p.user).name).toLocaleLowerCase().includes(searchTerm)&&(mediaFilter==='all'||(mediaFilter==='text'?!p.media:p.media?.type.startsWith(mediaFilter))));
 const neighbors=community.profiles.filter(p=>p.id!==community.me.id&&(p.name+' '+p.bio).toLocaleLowerCase().includes(searchTerm));
 const profilePosts=onlySaved?realPosts.filter(p=>saved.includes(p.id)):[...realPosts,...(activeProfile.id.startsWith('sample')?examples:[])].filter(p=>p.user===activeProfile.id);
 const unread=community.notifications.filter(n=>n.created>seen).length;
 const currentPost=selected?(community.posts.find(p=>p.id===selected.id)||selected):null;
 function toggleSaved(id:string){const next=saved.includes(id)?saved.filter(v=>v!==id):[...saved,id];setSaved(next);try{localStorage.setItem('vg-saved',JSON.stringify(next));}catch{setToast('이 기기에 저장하지 못했어요.');}}
 function postGrid(posts:Post[]){return <div className="story-grid">{posts.map((p,i)=><button className={'story-tile tile-'+i%3} key={p.id} onClick={()=>{setSelected(p);setDialog('detail');}} aria-label={findProfile(p.user).name+'님의 이야기 보기: '+p.caption.slice(0,45)}>{p.media?(<SocialMedia url={p.media.url} type={p.media.type} tile/>):<span className="tile-words"><span aria-hidden="true">“</span><span className="tile-excerpt">{p.caption}</span></span>}<span className="tile-type">{p.media?(p.media.type.startsWith('video')?<Film size={15}/>:<ImageIcon size={15}/>):<Type size={15}/>}</span><span className="tile-author">{findProfile(p.user).emoji} {findProfile(p.user).name}{p.sample?' · 예시':''}</span></button>)}</div>;}
 function promptCards(){return <div className="prompt-cards" aria-label="이야깃거리">{storyPrompts.map(p=><button key={p.id} className={'prompt-card '+p.color} onClick={()=>start('voice',p.question)}><span aria-hidden="true">{p.emoji}</span><strong>{p.title}</strong><small>{p.hint}</small><ArrowUpRight size={17}/></button>)}</div>;}
 function postCard(p:Post,i=0,detail=false){return <FeedPost key={p.id} post={p} author={findProfile(p.user)} me={community.me.id} following={community.following.includes(p.user)} saved={saved.includes(p.id)} busy={busy} speaking={speaking===p.id} priority={i===0} detail={detail} active={!dialog||detail} ago={p.sample?'예시':ago(p.created)} commentAuthor={p.comments.length?findProfile(p.comments[p.comments.length-1].user).name:undefined} onProfile={()=>openProfile(p.user)} onFollow={()=>void action({action:'follow',id:p.user,value:!community.following.includes(p.user)})} onMenu={()=>{setSelected(p);setDialog('postmenu');}} onLike={value=>void action({action:'like',id:p.id,value})} onComments={()=>{setSelected(p);setComment('');commentId.current=null;setDialog('comments');}} onShare={()=>void sharePost(p)} onSave={()=>toggleSaved(p.id)} onRead={()=>readPost(p)} onCreate={()=>go('create')}/>;}
 const nav=[{id:'home',label:'홈',icon:Home},{id:'explore',label:'둘러보기',icon:Search},{id:'create',label:'만들기',icon:Mic},{id:'notifications',label:'알림',icon:Bell},{id:'profile',label:'내 프로필',icon:User}];
 return <div className={'social-app '+(largeText?'large-text':'')}><aside className="social-sidebar"><button className="social-logo" onClick={()=>go('home')}><span><AudioLines size={27}/></span>보이스그램</button><p className="brand-tagline">말로 나누는, 우리 일상</p><nav aria-label="주 메뉴">{nav.map(({id,label,icon:Icon})=><button key={id} className={(view===id?'active ':'')+(id==='create'?'nav-create':'')} aria-current={view===id?'page':undefined} onClick={()=>go(id)}><Icon size={24}/>{label}{id==='notifications'&&unread>0&&<i className="unread-dot"/>}</button>)}</nav><div className="sidebar-bottom"><button className="person-button" onClick={()=>go('profile')}><span className="social-avatar">{community.me.emoji}</span><span><strong>{community.me.name}</strong><small>{status==='ready'?(community.authProvider==='kakao'?'카카오 계정':'테스트 프로필'):'둘러보는 중'}</small></span></button><button className="settings-link" onClick={()=>setDialog('settings')}><Settings size={17}/>설정 및 이용 안내</button></div></aside>
 <main className="social-main"><header className="social-topbar"><button className="social-logo" onClick={()=>go('home')}><span><AudioLines size={23}/></span>보이스그램</button><span className="desktop-title">{view==='billing'?'이용권 · 결제':view==='home'?'우리의 이야기':view==='explore'?'새로운 일상 발견':view==='create'?'내 이야기 만들기':view==='notifications'?'나에게 온 소식':'프로필'}</span><button className="icon-button" aria-label="설정" onClick={()=>setDialog('settings')}><Settings size={22}/></button></header>
 <div className="social-columns"><div className="social-center">
 {view==='home'&&<><section className="home-composer" aria-label="내 이야기 시작"><div className="home-greeting"><span className="social-avatar">{community.me.emoji}</span><div><h1>오늘은 어떤 이야기인가요?</h1><p>말 한마디도, 사진 한 장도 좋아요.</p></div></div><div className="quick-create"><button onClick={()=>start('voice')}><Mic size={21}/><strong>말로 만들기</strong></button><button onClick={()=>start('text')}><Type size={21}/><strong>글로 쓰기</strong></button></div></section><div className="feed-tabs"><div><button className={feedTab==='all'?'on':''} aria-pressed={feedTab==='all'} onClick={()=>{setFeedTab('all');setFeedLimit(12);}}>전체 피드</button><button className={feedTab==='following'?'on':''} aria-pressed={feedTab==='following'} onClick={()=>{setFeedTab('following');setFeedLimit(12);}}>팔로잉</button></div><button className="icon-button" aria-label="피드 새로고침" disabled={refreshing||busy} aria-busy={refreshing} onClick={()=>void refresh()}><RefreshCw size={19}/></button></div>{status==='loading'&&<div className="feed-skeleton" role="status" aria-label="피드를 불러오는 중"><div/><div/><div/><span>이야기를 불러오는 중…</span></div>}{status==='locked'&&<div className="connection-banner"><p>지금은 예시 피드를 보고 있어요.</p><button onClick={()=>setDialog('login')}>로그인하고 함께하기</button></div>}{status==='error'&&<div className="connection-banner"><p>{realPosts.length?'새 소식을 가져오지 못했어요. 마지막 피드를 보여드려요.':'피드를 불러오지 못했어요. 아래는 예시입니다.'}</p><button onClick={()=>void refresh()}>다시 연결</button></div>}{status==='ready'&&realPosts.length===0&&<div className="connection-banner"><p>아직 게시물이 없어요. 첫 이야기를 남겨주세요.</p></div>}{displayPosts.slice(0,feedLimit).map((p,i)=>postCard(p,i))}{displayPosts.length>feedLimit&&<button className="feed-more secondary" onClick={()=>setFeedLimit(n=>n+12)}>이야기 더 보기 <span>{Math.min(feedLimit,displayPosts.length)} / {displayPosts.length}</span></button>}{status==='ready'&&displayPosts.length>0&&!displayPosts[0].sample&&displayPosts.length<=feedLimit&&<div className="feed-end"><Check size={20}/><span>지금까지의 이야기를 모두 봤어요</span><button onClick={()=>go('explore')}>새 이웃 만나기</button></div>}{status!=='loading'&&!displayPosts.length&&<div className="social-empty"><span>🌱</span><h2>팔로우한 이웃의 이야기가 모여요</h2><p>전체 피드나 둘러보기에서 마음이 맞는 이웃을 찾아보세요.</p><button className="primary" onClick={()=>go('explore')}>이웃 둘러보기</button></div>}</>}
 {view==='explore'&&<><div className="page-heading"><h1>발견하는 즐거움</h1><p>다른 일상을 만나고, 내 이야기를 떠올려요.</p></div><label className="social-search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="이야기나 이름을 찾아보세요" aria-label="게시물과 프로필 검색"/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="검색어 지우기"><X size={18}/></button>}</label><div className="feed-tabs"><div><button className={exploreTab==='stories'?'on':''} aria-pressed={exploreTab==='stories'} onClick={()=>setExploreTab('stories')}>이야기</button><button className={exploreTab==='people'?'on':''} aria-pressed={exploreTab==='people'} onClick={()=>setExploreTab('people')}>사람</button></div></div>{exploreTab==='stories'?<><div className="interest-chips" role="group" aria-label="이야기 종류">{[['all','모두'],['image','사진'],['text','글'],['video','영상']].map(([v,l])=><button key={v} aria-pressed={mediaFilter===v} onClick={()=>setMediaFilter(v)}>{l}</button>)}</div>{!realPosts.length&&<p className="example-label">화면 체험용 예시 · 실제 사용자 글이 아니에요</p>}{postGrid(searchPosts)}{!searchPosts.length&&<div className="social-empty"><span>🔎</span><h2>아직 맞는 이야기가 없어요</h2><p>다른 검색어나 종류로 찾아보세요.</p><button className="secondary" onClick={()=>{setQuery('');setMediaFilter('all');}}>전체 이야기 보기</button></div>}{!query&&<section className="discovery-prompts"><h2>무슨 이야기를 할까?</h2><p>하나 골라, 편하게 말해보세요.</p>{promptCards()}</section>}</>:<>{neighbors.map(p=><div className="neighbor-row" key={p.id}><button className="person-button" onClick={()=>openProfile(p.id)}><span className="social-avatar">{p.emoji}</span><span><strong>{p.name}</strong><small>{p.bio||'새로운 이웃이에요'}</small></span></button><button className="follow-mini" disabled={busy} onClick={()=>void action({action:'follow',id:p.id,value:!community.following.includes(p.id)})}>{community.following.includes(p.id)?'팔로잉':'팔로우'}</button></div>)}{!neighbors.length&&<div className="social-empty"><span>👋</span><h2>{query?'찾는 이웃이 아직 없어요':'새로운 이웃을 기다려요'}</h2><p>{query?'다른 이름으로 찾아보세요.':'참여한 이웃이 생기면 여기에서 만날 수 있어요.'}</p></div>}</>}</>}
 {hasComposer&&status!=='loading'&&<div hidden={view!=='create'}><FeatureBoundary><Suspense fallback={<div className="feature-loading" role="status">이야기 만들기를 준비하고 있어요…</div>}><StoryComposer key={composeKey+':'+(community.me.id||'guest')} draftScope={community.me.id||'guest'} active={view==='create'} entryMode={entryMode} starter={starter} onPublish={publish} onClose={()=>go('home')}/></Suspense></FeatureBoundary></div>}
 {view==='billing'&&<FeatureBoundary><Suspense fallback={<div className="feature-loading" role="status">이용권 화면을 준비하고 있어요…</div>}><BillingPanel authenticated={auth.authenticated} onLogin={()=>setDialog('login')} onBack={()=>go('profile')}/></Suspense></FeatureBoundary>}
 {view==='notifications'&&<><div className="page-heading"><h1>알림</h1><p>내 이야기에 도착한 마음들</p></div>{community.notifications.length?community.notifications.map((n,i)=><button className="notification-row" key={n.type+n.user+n.created+i} onClick={()=>{if(n.type==='follow')openProfile(n.user);else{const p=community.posts.find(p=>p.id===n.post);if(p){setSelected(p);setComment('');commentId.current=null;setDialog('comments');}}}}><span className="social-avatar">{findProfile(n.user).emoji}</span><span><strong>{findProfile(n.user).name}</strong>님이 {n.type==='like'?'내 이야기를 좋아해요.':n.type==='comment'?'댓글을 남겼어요.':'나를 팔로우했어요.'}{n.body&&<em>{n.body}</em>}<small>{ago(n.created)}</small></span></button>):<div className="social-empty"><span>💌</span><h2>새로운 소식을 기다리고 있어요</h2><p>좋아요, 댓글, 팔로우가 생기면 알려드려요.<br/>앱을 열어 새로고침하면 확인할 수 있어요.</p></div>}<button className="secondary" onClick={()=>void refresh()}>새 소식 확인</button></>}
 {view==='profile'&&<><div className="profile-cover"><span>나답게 말하고, 함께 나누는 곳.</span><span aria-hidden="true">✦</span></div><section className="profile-info"><span className="profile-avatar">{activeProfile.emoji}</span><div className="profile-title"><h1>{activeProfile.name}</h1>{myProfile?<button className="profile-edit" onClick={()=>{if(!requireLogin())return;setName(community.me.name);setBio(community.me.bio);setEmoji(community.me.emoji);setDialog('edit');}}>프로필 편집</button>:!activeProfile.id.startsWith('sample')&&<button className="profile-edit" onClick={()=>void action({action:'follow',id:activeProfile.id,value:!community.following.includes(activeProfile.id)})}>{community.following.includes(activeProfile.id)?'팔로잉':'팔로우'}</button>}</div><p>{activeProfile.bio||'나의 하루를 이야기로 남겨보세요.'}</p><div className="profile-counts"><span><b>{[...realPosts,...examples].filter(p=>p.user===activeProfile.id).length}</b> {activeProfile.id.startsWith('sample')?'예시':'게시물'}</span>{myProfile&&<><button onClick={()=>setDialog('followers')}><b>{community.followers.length}</b> 팔로워</button><button onClick={()=>setDialog('following')}><b>{community.following.length}</b> 팔로잉</button></>}</div>{myProfile&&<p className="profile-beta">{community.authProvider==='kakao'?'카카오 계정으로 연결된 내 프로필':status==='ready'?'테스트용 기기 프로필':'로그인하면 나만의 이야기가 여기에 모여요.'}</p>}</section>{myProfile&&<div className="quick-create profile-create"><button onClick={()=>start('voice')}><span className="start-mic"><Mic size={24}/></span><span><strong>말로 만들기</strong></span></button><button onClick={()=>start('text')}><span className="write-symbol">✏️</span><span><strong>글로 쓰기</strong></span></button></div>}<div className="profile-account-actions">{myProfile&&<><button onClick={()=>setDialog('login')} className="text-button">{community.authProvider==='kakao'?'카카오 계정 연결됨':'카카오로 로그인'}</button><button className="text-button" onClick={()=>go('billing')}>이용권 · 결제 준비</button></>}</div><div className="feed-tabs profile-post-tabs"><div><button aria-pressed={!onlySaved} className={!onlySaved?'on':''} onClick={()=>setOnlySaved(false)}>게시물</button>{myProfile&&<button aria-pressed={onlySaved} className={onlySaved?'on':''} onClick={()=>setOnlySaved(true)}>저장한 글</button>}</div><div className="layout-switch"><button aria-label="모아보기" aria-pressed={layout==='grid'} onClick={()=>setLayout('grid')}><Grid2X2 size={19}/></button><button aria-label="크게 보기" aria-pressed={layout==='list'} onClick={()=>setLayout('list')}><Rows3 size={19}/></button></div></div>{onlySaved&&<p className="muted">저장 목록은 이 기기에 보관됩니다.</p>}{layout==='grid'?postGrid(profilePosts):profilePosts.map((p,i)=>postCard(p,i))}{profilePosts.length===0&&<div className="social-empty"><span>{onlySaved?'🔖':'📷'}</span><h2>{onlySaved?'마음에 드는 이야기를 저장해보세요':'아직 이야기가 없어요'}</h2>{myProfile&&!onlySaved&&<button className="primary" onClick={()=>go('create')}>첫 이야기 올리기</button>}</div>}</>}
 </div><aside className="social-right"><div className="right-welcome"><img src="/visuals/voicegram-world.webp" alt="말풍선과 사진으로 표현한 보이스그램" loading="lazy" decoding="async"/><h2>말 한마디로,<br/>더 가까워지는 우리.</h2><p>사진이 없어도, 멋진 글이 아니어도.<br/>당신의 이야기가 궁금해요.</p><button onClick={()=>go('create')}>내 이야기 나누기 <ArrowUpRight size={17}/></button></div><div className="right-prompt"><div><h3>오늘의 이야깃거리</h3><button className="icon-button" aria-label="다른 이야깃거리" onClick={()=>setPromptIndex(i=>(i+1)%storyPrompts.length)}><Shuffle size={17}/></button></div><span aria-hidden="true">{storyPrompts[promptIndex].emoji}</span><p>{storyPrompts[promptIndex].question}</p><button className="text-button" onClick={()=>start('voice',storyPrompts[promptIndex].question)}>이 이야기로 시작 <ArrowUpRight size={16}/></button></div><p className="right-foot">보이스그램 · JINI TEAM<br/><button onClick={()=>setDialog('settings')}>테스트 안내 · 개인정보</button></p></aside></div></main>
 <nav className="bottom-nav" aria-label="모바일 주 메뉴">{nav.map(({id,label,icon:Icon})=><button key={id} className={(view===id?'active ':'')+(id==='create'?'center-create':'')} aria-current={view===id?'page':undefined} onClick={()=>go(id)}><span><Icon size={id==='create'?25:23}/>{id==='notifications'&&unread>0&&<i className="unread-dot"/>}</span><small>{label}</small></button>)}</nav>
 {toast&&<div className="social-toast" role="status">{toast}</div>}
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v){setDialog('');setAuthError('');}}}><DialogContent className={'social-dialog '+(dialog==='detail'?'post-detail ':dialog==='comments'?'comments-sheet ':'')+(largeText?'large-text':'')}><DialogTitle>{dialog==='share'?'이야기 공유':dialog==='followers'?'팔로워':dialog==='following'?'팔로잉':dialog==='detail'?'이야기 보기':dialog==='login'?'가볍게 시작해요':dialog==='comments'?'이야기 나누기':dialog==='edit'?'내 프로필 꾸미기':dialog==='report'?'게시물 신고':dialog==='postmenu'?'게시물 메뉴':dialog==='delete'?'게시물을 삭제할까요?':'설정 및 이용 안내'}</DialogTitle><DialogDescription>{dialog==='share'?'링크로 이 이야기를 나눠보세요.':dialog==='followers'||dialog==='following'?'함께 이야기를 나누는 이웃들':dialog==='detail'?'사진과 글로 만나는 일상':dialog==='login'?'카카오 계정으로 내 이야기를 이어가세요.':dialog==='comments'?'다정한 한마디를 남겨주세요.':dialog==='edit'?'이웃들에게 보여줄 나를 소개해요.':dialog==='delete'?'삭제하면 피드에서 사라집니다. 되돌릴 수 없어요.':dialog==='report'?'신고 사유를 기록합니다. 자동 처리되지는 않습니다.':'보이스그램 테스트 공간'}</DialogDescription>
 {dialog==='detail'&&currentPost&&postCard(currentPost,0,true)}
 {dialog==='share'&&<div className="share-panel"><label htmlFor="post-link">게시물 링크</label><input id="post-link" readOnly value={shareUrl} onFocus={e=>e.target.select()}/><button className="primary" onClick={()=>void copyShare()}>링크 복사</button><p>현재는 테스트 공간이에요. 받는 사람도 접근 권한과 로그인이 필요합니다.</p></div>}
 {(dialog==='followers'||dialog==='following')&&<div className="connections-list">{(dialog==='followers'?community.followers:community.following).map(id=><div className="neighbor-row" key={id}><button className="person-button" onClick={()=>openProfile(id)}><span className="social-avatar">{findProfile(id).emoji}</span><span><strong>{findProfile(id).name}</strong><small>{findProfile(id).bio||'일상을 나누는 이웃'}</small></span></button><button className="follow-mini" disabled={busy} onClick={()=>void action({action:'follow',id,value:!community.following.includes(id)})}>{community.following.includes(id)?'팔로잉':'팔로우'}</button></div>)}{!(dialog==='followers'?community.followers:community.following).length&&<p className="empty-inline">아직 연결된 이웃이 없어요. 둘러보기에서 만나보세요.</p>}</div>}
 {dialog==='login'&&<div className="login-panel"><div className="login-symbol">💬</div><p>별도 비밀번호 없이,<br/><strong>카카오로 간편하게.</strong></p>{auth.authenticated?<><div className="account-connected"><Check size={19}/>카카오 계정으로 로그인되어 있어요.</div><button className="secondary" onClick={()=>setDialog('')}>이야기 나누러 가기</button></>:<><button className="kakao-button" onClick={kakaoLogin} disabled={!auth.kakaoReady||loginBusy}><svg width="21" height="21" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 3C6.5 3 2 6.5 2 10.7c0 2.7 1.8 5 4.5 6.4L5.4 21l4.6-2.7c.6.1 1.3.1 2 .1 5.5 0 10-3.4 10-7.7S17.5 3 12 3Z"/></svg>{loginBusy?'카카오로 이동 중…':'카카오로 시작하기'}</button><p className="login-note">{auth.kakaoReady?'카카오 동의 화면을 거쳐 보이스그램으로 돌아옵니다.':'간편로그인 연결을 준비하고 있어요. 연결 후 이용할 수 있습니다.'}</p></>}<div className="login-data-note">로그인 후 표시할 이름은 프로필에서 바꿀 수 있어요. 이메일·전화번호·카카오 친구 목록은 요청하지 않습니다. 카카오 계정과 이 기기의 테스트 글은 자동으로 합치지 않습니다.</div>{!auth.authenticated&&<details className="tester-access"><summary>초대받은 테스터인가요?</summary><p className="muted">기존 테스트 접근 코드로 참여할 수 있어요.</p><input type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} aria-label="테스트 접근 코드" placeholder="테스트 접근 코드"/><button className="secondary" onClick={unlock} disabled={busy||!code}>{busy?'연결 중…':'테스트 공간 참여'}</button></details>}{authError&&<p role="alert">{authError}</p>}</div>}
 {dialog==='edit'&&<><div className="avatar-choices">{['🙂','🌊','🌷','🐶','☕','🌳','🌙','🦋'].map(e=><button key={e} aria-label={e+' 프로필'} aria-pressed={e===emoji} onClick={()=>setEmoji(e)}>{e}</button>)}</div><label htmlFor="profile-name">이름</label><input id="profile-name" value={name} onChange={e=>setName(e.target.value)} maxLength={24}/><label htmlFor="profile-bio">한 줄 소개</label><textarea id="profile-bio" value={bio} onChange={e=>setBio(e.target.value)} maxLength={100} rows={2}/><button className="primary" disabled={busy||!name.trim()} onClick={async()=>{if(await action({action:'profile',name,bio,emoji})){setDialog('');setToast('프로필을 바꿨어요.');}}}>저장</button></>}
 {dialog==='comments'&&currentPost&&<><div className="comment-original">{currentPost.caption}</div><div className="comment-list">{currentPost.comments.length?currentPost.comments.map(c=><div className="comment-row" key={c.id}><span className="social-avatar">{findProfile(c.user).emoji}</span><div><strong>{findProfile(c.user).name}</strong><p>{c.body}</p><small>{ago(c.created)}</small></div>{c.user===community.me.id&&<button className="icon-button" aria-label="내 댓글 삭제" disabled={busy} onClick={()=>void action({action:'deleteComment',id:c.id})}><X size={17}/></button>}</div>):<p className="empty-inline">첫 댓글로 마음을 전해보세요.</p>}</div><div className="comment-replies" aria-label="댓글에 이모티콘 넣기">{['💜','👏','🥰','✨','🙌'].map(e=><button key={e} aria-label={e+' 댓글에 넣기'} disabled={busy||comment.length+e.length>500} onClick={()=>{setComment(v=>v+e);commentId.current=null;}}>{e}</button>)}</div><form className="comment-form" onSubmit={async e=>{e.preventDefault();commentId.current ||=crypto.randomUUID();if(await action({action:'comment',id:currentPost.id,body:comment,requestId:commentId.current})){setComment('');commentId.current=null;}}}><input disabled={busy} value={comment} onChange={e=>{setComment(e.target.value);commentId.current=null;}} aria-label="댓글" maxLength={500} placeholder="따뜻한 한마디…"/><button className="icon-button" disabled={busy||!comment.trim()} aria-label="댓글 보내기"><Send size={21}/></button></form></>}
 {dialog==='postmenu'&&currentPost&&<>{currentPost.user===community.me.id?<button className="menu-action danger" onClick={()=>setDialog('delete')}>내 게시물 삭제</button>:<><button className="menu-action" onClick={()=>{setReport('');setDialog('report');}}>신고하기</button><button className="menu-action" disabled={busy} onClick={async()=>{if(await action({action:'block',id:currentPost.user,value:true})){setDialog('');setToast('이 사용자의 게시물과 댓글을 숨겼어요. 설정에서 해제할 수 있어요.');}}}>이 사용자 차단</button></>}</>}
 {dialog==='delete'&&currentPost&&<><button className="primary" disabled={busy} onClick={async()=>{if(await action({action:'delete',id:currentPost.id})){setDialog('');setToast('게시물을 삭제했어요.');}}}>삭제하기</button><button className="secondary" onClick={()=>setDialog('')}>취소</button></>}
 {dialog==='report'&&currentPost&&<><textarea aria-label="신고 사유" value={report} onChange={e=>setReport(e.target.value)} maxLength={500} rows={3}/><button className="primary" disabled={busy||!report.trim()} onClick={async()=>{if(await action({action:'report',id:currentPost.id,reason:report})){setDialog('');setToast('신고를 기록했어요. 바로 숨기려면 사용자 차단을 이용해주세요.');}}}>신고 기록하기</button></>}
 {dialog==='settings'&&<div className="settings-content"><div className="reading-setting"><div><h3>글씨 크게 보기</h3><p>피드와 게시글을 편하게 읽어요.</p></div><button role="switch" aria-label="글씨 크게 보기" aria-checked={largeText} onClick={()=>{const next=!largeText;setLargeText(next);try{localStorage.setItem('vg-large-text',String(next));}catch{}}}>{largeText?'켜짐':'꺼짐'}</button></div><h3>현재 연결</h3><p>{community.authProvider==='kakao'?'카카오 계정 로그인됨':status==='ready'?'테스트 공간 연결됨':'로그인 전'}</p>{status!=='ready'&&<button className="primary" onClick={()=>setDialog('login')}>카카오로 시작하기</button>}<button className="secondary" onClick={()=>{setDialog('');go('billing');}}>이용권 · 토스페이 준비 상태</button>{status==='ready'&&<button className="text-button" onClick={logout} disabled={busy}>이 기기에서 로그아웃</button>}<h3>내 정보와 게시물</h3><p>게시물·댓글·프로필·좋아요·팔로우는 서버에 저장되며 테스터가 볼 수 있어요. 임시 작성글과 저장 목록은 이 기기에 보관됩니다. 카카오 로그인은 같은 계정의 프로필을 다시 찾도록 준비되어 있습니다. 기존 기기 테스트 프로필과 카카오 계정은 별도로 유지됩니다.</p><h3>말로 만들기</h3><p>마이크 권한이 필요하고 브라우저에 따라 음성 입력 지원이 달라요. 음성은 브라우저의 인식 서비스에 전달될 수 있습니다. AI 다듬기를 사용하면 대화와 문구가 OpenAI에 전달되고 API 사용료가 발생합니다. 이동 중에는 안전하게 멈춘 뒤 확인하고 게시해주세요.</p><h3>차단한 사용자</h3>{community.blocked.length?community.blocked.map(b=><div className="neighbor-row" key={b.id}><span>{b.name}</span><button className="text-button" disabled={busy} onClick={()=>void action({action:'block',id:b.id,value:false})}>차단 해제</button></div>):<p>차단한 사용자가 없어요.</p>}<p className="muted">인스타그램 연결은 보류 중입니다. 이 피드는 보이스그램 안에서 나누는 이야기예요. 카카오 실로그인 검증·신고 처리·운영 정책을 갖춘 뒤 정식 공개합니다.</p></div>}
 </DialogContent></Dialog></div>;
}
