'use client';
import {useEffect,useRef,useState} from 'react';
import {CreditCard,ShieldCheck,ArrowLeft,RefreshCw} from 'lucide-react';
type Order={orderId:string;orderName:string;amount:number;currency:string;customerKey:string;clientKey:string;variantKey:string;successUrl:string;failUrl:string;mode:string};
type Confirm={paymentKey:string;orderId:string;amount:number};
type Widgets={setAmount:(x:{value:number;currency:string})=>Promise<void>;renderPaymentMethods:(x:{selector:string;variantKey:string})=>Promise<{destroy:()=>Promise<void>}>;renderAgreement:(x:{selector:string;variantKey:string})=>Promise<{destroy:()=>Promise<void>}>;requestPayment:(x:Record<string,unknown>)=>Promise<void>};
let sdkPromise:Promise<void>|null=null;
function loadSdk(){if((window as any).TossPayments)return Promise.resolve();if(sdkPromise)return sdkPromise;sdkPromise=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://js.tosspayments.com/v2/standard';script.async=true;script.onload=()=>resolve();script.onerror=()=>{script.remove();sdkPromise=null;reject(Error('결제창을 불러오지 못했어요. 다시 시도해주세요.'));};document.head.appendChild(script);});return sdkPromise;}
export default function BillingPanel({authenticated,onLogin,onBack}:{authenticated:boolean;onLogin:()=>void;onBack:()=>void}){
 const [config,setConfig]=useState<{ready:boolean;mode:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[order,setOrder]=useState<Order|null>(null),[widgetReady,setWidgetReady]=useState(false),[result,setResult]=useState(''),[confirmation,setConfirmation]=useState<Confirm|null>(null);
 const widgets=useRef<Widgets|null>(null),inflight=useRef(false),initialized=useRef(false);
 useEffect(()=>{fetch('/api/billing').then(async r=>{if(!r.ok)throw Error();setConfig(await r.json() as {ready:boolean;mode:string});}).catch(()=>setError('결제 준비 상태를 확인하지 못했어요. 잠시 후 다시 확인해주세요.'));},[]);
 useEffect(()=>{if(initialized.current)return;initialized.current=true;const q=new URLSearchParams(location.search);const status=q.get('payment');if(!status)return;history.replaceState(null,'',location.pathname);if(status==='fail'){setResult('결제가 취소되었거나 완료되지 않았어요.');return;}if(status==='success'){const amount=Number(q.get('amount'));if(!q.get('paymentKey')||!q.get('orderId')||!Number.isSafeInteger(amount)){setError('결제 결과 정보가 올바르지 않아요.');return;}const input={paymentKey:q.get('paymentKey')!,orderId:q.get('orderId')!,amount};setConfirmation(input);void confirm(input);}},[]);
 useEffect(()=>{if(!order)return;let cancelled=false;const instances:{destroy:()=>Promise<void>}[]=[];setWidgetReady(false);(async()=>{try{await loadSdk();if(cancelled)return;const w=(window as any).TossPayments(order.clientKey).widgets({customerKey:order.customerKey}) as Widgets;widgets.current=w;await w.setAmount({value:order.amount,currency:order.currency});if(cancelled)return;instances.push(await w.renderPaymentMethods({selector:'#vg-payment-methods',variantKey:order.variantKey}));if(cancelled){for(const i of instances)void i.destroy();return;}instances.push(await w.renderAgreement({selector:'#vg-payment-agreement',variantKey:'AGREEMENT'}));if(cancelled){for(const i of instances)void i.destroy();return;}setWidgetReady(true);}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'결제창을 준비하지 못했어요.');}})();return()=>{cancelled=true;widgets.current=null;for(const i of instances)void i.destroy();};},[order]);
 async function confirm(input:Confirm){if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',...input})});const d=await r.json() as {error?:string;paid?:boolean;mode?:string};if(!r.ok||!d.paid||d.mode!=='test')throw Error(d.error||'승인 결과를 확인하지 못했어요.');setResult('테스트 승인을 확인했어요. 실제 청구와 이용권 지급은 없습니다.');setConfirmation(null);}catch(e){setError(e instanceof Error?e.message:'승인 결과를 확인하지 못했어요.');}finally{inflight.current=false;setBusy(false);}}
 async function prepare(){if(!authenticated){onLogin();return;}if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'order',requestId:crypto.randomUUID()})});const data=await r.json() as Order&{error?:string};if(!r.ok)throw Error(data.error||'주문을 만들지 못했어요.');setOrder(data);}catch(e){setError(e instanceof Error?e.message:'주문을 만들지 못했어요.');}finally{inflight.current=false;setBusy(false);}}
 async function pay(){if(!order||!widgets.current||busy)return;setBusy(true);setError('');try{await widgets.current.requestPayment({orderId:order.orderId,orderName:order.orderName,successUrl:order.successUrl,failUrl:order.failUrl,windowTarget:'self'});}catch{setError('결제창이 닫혔거나 요청이 완료되지 않았어요.');}finally{setBusy(false);}}
 return <section className="billing-page"><header className="compose-header"><button className="icon-button" onClick={onBack} aria-label="프로필로 돌아가기"><ArrowLeft size={22}/></button><h1>이용권 · 결제</h1></header><div className="billing-hero"><span><CreditCard size={32}/></span><h2>더 자유롭게 만드는 방법</h2><p>AI 이미지와 영상 이용권을 준비하고 있어요.<br/>가격과 제공 범위는 출시 전에 안내할게요.</p></div><div className="payment-option"><span className="toss-mark">toss</span><div><strong>토스페이</strong><small>{config?.ready?'테스트 연결 가능 · 실제 청구 없음':'간편결제 연결 준비 중'}</small></div><span className="soon-badge">준비 중</span></div><div className="billing-note"><ShieldCheck size={20}/><p>지금은 유료 상품을 판매하지 않아요.<small>자동 결제나 정기 구독도 시작되지 않습니다.</small></p></div>{config?.ready&&!order&&!confirmation&&<button className="secondary" onClick={prepare} disabled={busy}>테스트 결제 확인하기</button>}{order&&<div className="test-checkout"><h3>연동 테스트 · {order.amount.toLocaleString()}원</h3><p className="muted">실제 청구되지 않는 테스트 금액입니다. 결제수단에서 토스페이를 선택하세요. 테스트 상점 설정에 따라 표시 수단이 달라질 수 있어요.</p><div id="vg-payment-methods"/><div id="vg-payment-agreement"/><button className="primary" onClick={pay} disabled={!widgetReady||busy}>{busy?'확인 중…':'테스트 결제 진행'}</button></div>}{error&&<p className="compose-notice error" role="alert">{error}</p>}{confirmation&&<button className="secondary" onClick={()=>void confirm(confirmation)} disabled={busy}><RefreshCw size={16}/>{busy?'승인 확인 중…':'새 결제 없이 결과 다시 확인'}</button>}{result&&<p className="compose-notice" role="status">{result}</p>}<button className="text-button draft-load" onClick={onBack}>내 프로필로 돌아가기</button></section>;
}
