'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Send,Undo2,AudioLines,Loader2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {parseCommand} from '@/lib/commands';
import type {Design} from '@/lib/artwork';
type Snapshot={design:Design;caption:string;kind:string};
type Turn={role:'user'|'assistant';text:string;mode?:string};
type Changes=Partial<Design>&{caption?:string;kind?:string};
type Props=Snapshot&{disabled:boolean;onChange:(c:Changes)=>void;onAction:(action:string,request:string)=>void};
export default function Conversation(p:Props){
 const [turns,setTurns]=useState<Turn[]>([{role:'assistant',text:'어떤 순간을 남기고 싶으세요? 사진이 있다면 먼저 넣고, 원하는 느낌을 이야기해주세요.',mode:'안내'}]),[input,setInput]=useState(''),[pending,setPending]=useState(false),[listening,setListening]=useState(false),[interim,setInterim]=useState(''),[connected,setConnected]=useState(false),[configured,setConfigured]=useState(false),[dialog,setDialog]=useState(false),[code,setCode]=useState(''),[authError,setAuthError]=useState(''),[undoCount,setUndoCount]=useState(0);
 const end=useRef<HTMLDivElement>(null),recognition=useRef<any>(null),inflight=useRef(false),past=useRef<Snapshot[]>([]),previous=useRef<Snapshot>({design:p.design,caption:p.caption,kind:p.kind}),skip=useRef(false),sendRef=useRef<(t:string)=>void>(()=>{});
 const add=(text:string,mode='기본 편집')=>setTurns(t=>[...t.slice(-29),{role:'assistant',text,mode}]);
 useEffect(()=>{fetch('/api/chat').then(r=>r.json() as Promise<{configured:boolean;authenticated:boolean}>).then(d=>{setConfigured(!!d.configured);setConnected(!!d.authenticated);}).catch(()=>{});return()=>recognition.current?.abort();},[]);
 useEffect(()=>{const current={design:p.design,caption:p.caption,kind:p.kind};if(JSON.stringify(current)!==JSON.stringify(previous.current)){if(skip.current)skip.current=false;else past.current=[...past.current.slice(-11),previous.current];previous.current=current;setUndoCount(past.current.length);}},[p.design,p.caption,p.kind]);
 useEffect(()=>{if(turns.length>1||pending)end.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[turns,pending]);
 function undo(){const last=past.current.pop();if(!last){add('아직 되돌릴 수정이 없어요.');return;}skip.current=true;p.onChange({...last.design,caption:last.caption,kind:last.kind});setUndoCount(past.current.length);add('바로 전 편집 상태로 되돌렸어요.');}
 async function send(raw:string){const text=raw.trim();if(!text||inflight.current||p.disabled)return;if(text.length>2000){add('한 번에 2,000자 이내로 이야기해주세요.','안내');return;}setInput('');setInterim('');setTurns(t=>[...t.slice(-29),{role:'user',text}]);const parsed=parseCommand(text);
 // Local control actions never need a paid model and never publish externally.
 if(/^(아까|이전|방금|원래)(대로|처럼| 상태로| 사진으로)?\s*(돌려줘|되돌려줘|돌아가|복원해줘|다시)[.!]?$/u.test(text)||/^(취소|되돌려|되돌리기|한 단계 뒤로)[.!]?$/u.test(text)){undo();return;}
 if(!connected&&/(글씨|글자|문구|텍스트).*(빼|없애|지워|숨겨)/.test(text)){p.onChange({showText:false});add('이미지 위의 글씨를 숨겼어요. 원래 문구는 그대로 보관돼요.');return;}
 if(!connected&&/(글씨|글자|문구|텍스트).*(다시|보이|넣어)/.test(text)){p.onChange({showText:true});add('글씨를 다시 보여드릴게요.');return;}
 if(['create','save'].includes(parsed.action)||(!connected&&parsed.action==='share')){p.onAction(parsed.action,text);add(parsed.action==='share'?'공유 전에 확인할 화면을 열었어요. 아직 게시하지 않았어요.':parsed.action==='save'?'파일 저장을 요청할게요. 기기에서 완료 여부를 확인해주세요.':'지금 편집한 내용으로 만들기를 요청할게요.');return;}
 if(!connected){if(parsed.action==='bigger'){p.onChange({fontSize:Math.min(138,p.design.fontSize+12)});add('제목을 조금 더 크게 바꿨어요.');}else if(parsed.action==='smaller'){p.onChange({fontSize:Math.max(60,p.design.fontSize-12)});add('제목을 조금 줄였어요.');}else if(parsed.action==='headline'){p.onChange({headline:parsed.value,showText:true});add('제목을 바꿨어요. 오른쪽 게시물에서 확인해주세요.');}else if(parsed.action==='style'){p.onChange({theme:parsed.value});add('글씨와 배경의 분위기를 바꿨어요. 사진 자체의 색감은 바꾸지 않았어요.');}else{p.onAction('stage',text);add('이야기를 제작 요청에 담아두었어요. 다만 지금은 자유 대화 AI가 연결되지 않아 이 뜻을 이해하고 새 내용을 만들 수는 없어요. 사진·문구 편집은 계속 사용할 수 있어요.','AI 연결 필요');}return;}
 inflight.current=true;setPending(true);try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:turns.slice(-16),state:{...p.design,photo:undefined,hasPhoto:!!p.design.photo,caption:p.caption,kind:p.kind}})});const data=await response.json() as {error?:string;code?:string;message:string;action:string;changes:Record<string,unknown>};if(!response.ok){if(data.code==='AUTH_REQUIRED')setConnected(false);throw Error(data.error||'답변을 받지 못했어요.');}if(data.action==='undo'){undo();return;}const patch:Changes={};for(const [key,limit] of [['headline',60],['subtitle',80],['brand',25],['caption',2200]] as const)if(typeof data.changes?.[key]==='string')patch[key]=(data.changes[key] as string).slice(0,limit);if(['classic','fresh','pop'].includes(String(data.changes?.theme)))patch.theme=String(data.changes.theme);if(['image','video'].includes(String(data.changes?.kind)))patch.kind=String(data.changes.kind);if(['1:1','4:5','9:16'].includes(String(data.changes?.ratio)))patch.ratio=String(data.changes.ratio);if((patch.kind||p.kind)==='video')patch.ratio='9:16';if(typeof data.changes?.fontSize==='number'&&Number.isFinite(data.changes.fontSize))patch.fontSize=Math.max(60,Math.min(138,data.changes.fontSize));if(typeof data.changes?.showText==='boolean')patch.showText=data.changes.showText;if(Object.keys(patch).length)p.onChange(patch);add(data.message.slice(0,2000),'AI 대화');if(data.action==='review')p.onAction('share',text);if(data.action==='generate')p.onAction('generate',text);
 }catch(e){add(e instanceof Error?e.message:'대화 연결에 문제가 생겼어요. 편집 내용은 유지했어요.','연결 오류');}finally{inflight.current=false;setPending(false);}}
 sendRef.current=t=>{void send(t);};
 function mic(){if(listening){recognition.current?.stop();return;}const C=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!C){add('입력칸을 누르고 휴대폰 키보드의 마이크로 말해주세요. 이 브라우저는 앱 안의 음성 입력을 지원하지 않아요.','안내');return;}const r=new C();r.lang='ko-KR';r.interimResults=true;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>{setListening(false);setInterim('');};r.onresult=(e:any)=>{const t=Array.from(e.results).map((v:any)=>v[0].transcript).join('');setInterim(t);if(e.results[e.results.length-1].isFinal)sendRef.current(t);};r.onerror=(e:any)=>{setListening(false);add(e.error==='not-allowed'?'마이크 사용을 허용해주세요. 글로 입력해도 괜찮아요.':'음성을 듣지 못했어요. 다시 말하거나 글로 입력해주세요.','안내');};recognition.current=r;try{r.start();}catch{add('마이크를 시작하지 못했어요. 글로 입력해주세요.','안내');}}
 async function unlock(){if(inflight.current)return;inflight.current=true;setAuthError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'unlock',code})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setConnected(true);setCode('');setDialog(false);add('AI 대화가 연결됐어요. 앞선 이야기와 현재 편집 내용을 함께 보며 도와드릴게요.','연결');}catch(e){setAuthError(e instanceof Error?e.message:'연결에 실패했어요.');}finally{inflight.current=false;}}
 return <section className="conversation"><div className="conversation-title"><span><AudioLines size={18}/>함께 만들어요</span><button onClick={()=>setDialog(true)} className={'connection-tag '+(connected?'online':'')}>{connected?'AI 대화 연결됨':configured?'AI 대화 시작하기':'기본 편집 · AI 연결 전'}</button></div><div className="turns" role="log" aria-live="polite" aria-label="제작 대화">{turns.map((t,i)=><div className={'turn '+t.role} key={i}>{t.role==='assistant'&&<small>{t.mode}</small>}<p>{t.text}</p></div>)}{pending&&<div className="turn assistant"><p><Loader2 size={15} style={{display:'inline',marginRight:6}}/>이야기와 편집 내용을 살펴보고 있어요…</p></div>}<div ref={end}/></div><div className="conversation-suggestions">{['글씨는 빼줘','이대로 만들어줘','공유 준비해줘'].map(t=><button key={t} disabled={p.disabled||pending} onClick={()=>send(t)}>{t}</button>)}</div><form onSubmit={e=>{e.preventDefault();void send(input);}} className="chat-composer"><label htmlFor="chat-message" className="sr-only">보이스그램에게 이야기하기</label><textarea id="chat-message" value={input} onChange={e=>setInput(e.target.value)} maxLength={2000} rows={2} disabled={pending||p.disabled} placeholder="예: 좀 더 따뜻한 말투로 바꿔줘" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send(input);}}}/><div className="composer-controls"><button type="button" className={'voice-button '+(listening?'recording':'')} onClick={mic} disabled={pending||p.disabled} aria-pressed={listening}>{listening?<Square size={18}/>:<Mic size={19}/>} {listening?'그만 듣기':'말로 이야기'}</button><button type="submit" className="send-button" disabled={!input.trim()||pending||p.disabled||listening} aria-label="메시지 보내기"><Send size={19}/></button></div>{listening&&<p className="listening-text" role="status">{interim||'듣고 있어요…'}</p>}</form><div className="chat-footer"><span>대화는 현재 작업 중에만 유지돼요.</span><button disabled={!undoCount||pending||p.disabled} onClick={undo}><Undo2 size={14}/>되돌리기</button></div><Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogTitle>자유로운 AI 대화 연결</DialogTitle><DialogDescription>{configured?'테스트 접근 코드를 입력하면 AI 대화를 시작할 수 있어요.':'현재 AI API 키와 테스트 접근 설정이 연결되지 않았습니다.'}</DialogDescription>{configured?<><p className="dialogcopy">대화와 현재 문구가 OpenAI에 전달되며 연결된 API 계정에 사용료가 발생합니다. 사진 파일은 이 대화 기능에 보내지 않습니다.</p><input type="password" aria-label="테스트 접근 코드" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)}/><button className="primary" onClick={unlock}>확인하고 AI 대화 연결</button>{authError&&<p role="alert">{authError}</p>}</>:<p className="dialogcopy">현재는 글씨 숨기기·크기 조절·제목 변경·만들기·저장·공유 준비 같은 기본 편집을 지원해요. “좀 더 따뜻하게 써줘” 같은 요청은 AI 연결 후 이용할 수 있습니다.</p>}</DialogContent></Dialog></section>;
}
