'use client';
import {useEffect,useState,useRef} from 'react';
type Props={getFile:()=>Promise<Blob>;caption:string;disabled:boolean};
export default function InstagramPublisher({getFile,caption,disabled}:Props){
 const [account,setAccount]=useState<{connected:boolean;configured:boolean;username?:string}>({connected:false,configured:false}),[username,setUsername]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState(''),[status,setStatus]=useState(''),[link,setLink]=useState(''),[confirmed,setConfirmed]=useState(false);const locked=useRef(false);
 const api=async(body:unknown)=>{const r=await fetch('/api/instagram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'연결을 확인해주세요.');return d;};
 async function refresh(){try{const r=await fetch('/api/instagram');const d=await r.json() as any;if(!r.ok)throw Error(d.error);setAccount(d);}catch(e){setMessage((e as Error).message);}}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{setDraft('');setStatus('');setConfirmed(false);setLink('');},[caption]);
 async function run(task:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setMessage('');try{await task();}catch(e){setMessage((e as Error).message);}finally{locked.current=false;setBusy(false);}}
 async function prepare(){await run(async()=>{setDraft('');setStatus('');setConfirmed(false);const b=await getFile();let out=b;if(b.type.startsWith('image/')){const bitmap=await createImageBitmap(b);const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const ctx=c.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bitmap,0,0);bitmap.close();out=await new Promise<Blob>((resolve,reject)=>c.toBlob(v=>v?resolve(v):reject(Error('이미지 변환 실패')),'image/jpeg',.9));}if(out.type!=='image/jpeg'&&out.type!=='video/mp4')throw Error('인스타 직접 게시에는 JPG 또는 MP4가 필요합니다. WebM은 파일 저장 후 변환해주세요.');if(out.size>4000000)throw Error('현재 직접 게시 파일은 4MB까지 지원합니다. 큰 영상은 저장 후 인스타에서 올려주세요.');const f=new FormData();f.set('file',out,out.type==='image/jpeg'?'post.jpg':'reel.mp4');const r=await fetch('/api/media',{method:'POST',body:f});const upload=await r.json() as {error?:string;assetId:string};if(!r.ok)throw Error(upload.error);const d=await api({action:'prepare',assetId:upload.assetId,caption});setDraft(d.draftId);setStatus('IN_PROGRESS');setMessage('파일을 인스타에 전달했습니다. 아직 게시하지 않았습니다. 처리 상태를 확인해주세요.');});}
 return <section className="instagram-publisher"><h3>내 인스타그램에 게시</h3>{account.connected?<p>연결 계정: <strong>@{account.username}</strong></p>:<><label htmlFor="instagram-username">내 인스타 아이디</label><input id="instagram-username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="@아이디" autoComplete="off"/><p className="fine">비즈니스·크리에이터 계정을 연결하세요. 비밀번호는 인스타 공식 로그인 화면에서만 입력합니다.</p><button className="secondary" disabled={busy||disabled||!username.trim()} onClick={()=>run(async()=>{const d=await api({action:'connect',username});window.location.assign(d.url);})}>인스타 공식 로그인으로 연결</button>{!account.configured&&<p className="fine">Meta 앱 설정이 아직 필요합니다.</p>}</>}
 {account.connected&&<><button className="secondary" disabled={busy||disabled} onClick={prepare}>이 완성본과 게시글로 게시 준비</button>{draft&&<><p className="fine">{status==='FINISHED'?'인스타 처리 완료 · 최종 확인 후 게시할 수 있어요.':'인스타 파일 처리 중 · 아직 게시되지 않았어요.'}</p><button className="secondary" disabled={busy} onClick={()=>run(async()=>{const d=await api({action:'status',draftId:draft});setStatus(d.status);if(['ERROR','EXPIRED'].includes(d.status))setMessage('인스타가 파일을 처리하지 못했습니다. 파일 형식을 확인해주세요.');})}>처리 상태 확인</button><label style={{display:'flex',gap:10,margin:'16px 0'}}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> @{account.username}에 공개 게시하는 것을 확인합니다.</label><button className="primary" disabled={busy||disabled||status!=='FINISHED'||!confirmed} onClick={()=>run(async()=>{const d=await api({action:'publish',draftId:draft,username:account.username,confirmed:true});setStatus('PUBLISHED');setMessage('인스타그램 게시가 완료됐습니다.');if(d.permalink)setLink(d.permalink);})}>확인한 계정에 지금 게시</button></>}{link&&<a href={link} target="_blank" rel="noreferrer">게시된 인스타그램 열기</a>}<button className="plain" disabled={busy} onClick={()=>run(async()=>{await api({action:'disconnect'});setAccount({connected:false,configured:true});setDraft('');})}>이 기기 연결 해제</button></>}
 <button className="plain" disabled={busy} onClick={refresh}>연결 상태 새로 확인</button>{message&&<p role="status" className="notice">{message}</p>}{busy&&<p role="status">처리 중입니다. 중복 요청하지 마세요…</p>}</section>;
}
