'use client';
import {useEffect,useRef,useState} from 'react';
import {ImagePlus,ArrowUpRight,ChevronRight,Sparkles,ShieldCheck,Mic,Type,Image as ImageIcon,Film,Shuffle,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {creationIntent} from '@/lib/creation-intent';
import {storyPrompts} from '@/lib/story-prompts';
import Conversation from '@/components/conversation';


import {Design,loadImage,paint,renderPng,renderVideo,palettes} from '@/lib/artwork';
const initial:Design={headline:'',subtitle:'',brand:'',theme:'classic',ratio:'4:5',fontSize:104,photo:'',showText:false};
type Job={id:string;token:string;status:string;progress:number};
export default function Studio({onPublish,onClose,entryMode,active,starter}:{starter?:{id:number;question:string}|null;active:boolean;entryMode:'voice'|'text';onPublish:(file:Blob|null,caption:string,ai:boolean)=>Promise<void>;onClose:()=>void}){
 const [question,setQuestion]=useState(''),[promptIndex,setPromptIndex]=useState(0),[code,setCode]=useState(''),[authError,setAuthError]=useState(''),[aiAuthenticated,setAiAuthenticated]=useState(false),[literalText,setLiteralText]=useState(false);
 useEffect(()=>{if(starter){setQuestion(starter.question);setStep(1);}},[starter?.id]);
 const [mode,setMode]=useState(entryMode),[step,setStep]=useState(1),[publishing,setPublishing]=useState(false),[aiMade,setAiMade]=useState(false);
 const [design,setDesign]=useState<Design>(initial),[brief,setBrief]=useState(''),[kind,setKind]=useState('text'),[source,setSource]=useState('photo'),[caption,setCaption]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(false),[dialog,setDialog]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[file,setFile]=useState<Blob|null>(null),[videoUrl,setVideoUrl]=useState(''),[job,setJob]=useState<Job|null>(null),[imageReady,setImageReady]=useState(false),[videoReady,setVideoReady]=useState(false);
 useEffect(()=>{setMode(entryMode);if(entryMode==='text')setTimeout(()=>document.getElementById('story-caption')?.focus(),100);},[entryMode]);
 useEffect(()=>{const preserve=()=>{try{sessionStorage.setItem('vg-login-draft',JSON.stringify({...state.current,source,step,aiMade,expires:Date.now()+86400000}));}catch{}};window.addEventListener('voicegram-before-login',preserve);return()=>window.removeEventListener('voicegram-before-login',preserve);},[source,step,aiMade]);
 useEffect(()=>{try{const raw=sessionStorage.getItem('vg-login-draft');if(!raw)return;const d=JSON.parse(raw);if(d.expires>Date.now()&&d.design&&palettes[d.design.theme]){setDesign({...initial,...d.design});setCaption(d.caption||'');setBrief(d.brief||'');setKind(['text','image','video'].includes(d.kind)?d.kind:'text');setSource(d.source==='ai'?'ai':'photo');setAiMade(!!d.aiMade);setStep(1);message('로그인 전에 작성하던 이야기를 불러왔어요.');}sessionStorage.removeItem('vg-login-draft');}catch{}},[]);
 const aiReady=kind==='image'?imageReady:videoReady;
 const canvas=useRef<HTMLCanvasElement>(null),input=useRef<HTMLInputElement>(null),state=useRef({design,brief,caption,kind}),applyPhoto=useRef(0),busyRef=useRef(false);
 state.current={design,brief,caption,kind};
 const message=(s:string,err=false)=>{setNotice(s);setError(err);};
 useEffect(()=>{const check=()=>fetch('/api/studio').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{image:boolean;video:boolean;authenticated?:boolean}>;}).then(d=>{setImageReady(d.image);setVideoReady(d.video);setAiAuthenticated(!!d.authenticated);}).catch(()=>{});void check();window.addEventListener('voicegram-auth',check);return()=>window.removeEventListener('voicegram-auth',check);},[]);
 useEffect(()=>{let active=true;loadImage(design.photo).then(im=>{if(active&&canvas.current)paint(canvas.current,design,im);}).catch(e=>message(e.message,true));setFile(null);setVideoUrl('');return()=>{active=false;};},[design,kind]);
 useEffect(()=>{if(!file||!file.type.startsWith('video/'))return;const url=URL.createObjectURL(file);setVideoUrl(url);return()=>URL.revokeObjectURL(url);},[file]);
 useEffect(()=>{if(!job||['completed','failed','paused'].includes(job.status))return;let active=true;let timer:ReturnType<typeof setTimeout>;const started=Date.now();const poll=async()=>{try{const r=await fetch(`/api/studio?id=${encodeURIComponent(job.id)}&token=${job.token}`);const data=await r.json() as {status:string;progress:number;error?:string};if(!r.ok)throw Error(data.error||"상태 확인에 실패했습니다.");if(!active)return;setJob(j=>j?{...j,status:data.status,progress:data.progress||0}:null);if(data.status==='completed'){const res=await fetch(`/api/studio?id=${encodeURIComponent(job.id)}&token=${job.token}&download=1`);if(!res.ok)throw Error('완성 영상 다운로드에 실패했습니다. 상태를 다시 확인해주세요.');const blob=await res.blob();if(active){setFile(blob);setAiMade(true);setBusy(false);busyRef.current=false;message('AI 영상이 완성되었습니다. 재생해서 확인한 뒤 저장해주세요.');}return;}if(data.status==='failed')throw Error(data.error||'영상 생성에 실패했습니다.');if(Date.now()-started>600000)throw Error('생성이 오래 걸리고 있습니다. 상태 다시 확인을 눌러주세요. 새 생성 요청은 보내지 않습니다.');timer=setTimeout(poll,5000);}catch(e){if(active){setBusy(false);busyRef.current=false;setJob(j=>j?{...j,status:'paused'}:null);message(e instanceof Error?e.message:'영상 상태 확인에 실패했습니다.',true);}}};timer=setTimeout(poll,2500);return()=>{active=false;clearTimeout(timer);};},[job?.id,job?.token,job?.status==='paused']);
 async function upload(f?:File){if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024){message('10MB 이하의 JPG, PNG, WebP 사진을 선택해주세요. HEIC는 JPG로 변환해주세요.',true);return;}const seq=++applyPhoto.current;try{const url=URL.createObjectURL(f);try{const im=await loadImage(url);if(!im)throw Error();const c=document.createElement('canvas');const scale=Math.min(1,2048/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d')!.drawImage(im,0,0,c.width,c.height);if(seq===applyPhoto.current){setDesign(d=>({...d,photo:c.toDataURL('image/jpeg',.9)}));message('사진을 넣었습니다. 문구와 분위기를 바꿔보세요.');}}finally{URL.revokeObjectURL(url);}}catch{message('사진을 읽지 못했습니다. 다른 사진을 선택해주세요.',true);}}
 async function create(){if(busyRef.current)return;if(source==='ai'){if(!brief.trim()){message('만들고 싶은 장면을 먼저 말하거나 입력해주세요.',true);return;}setAuthError('');setDialog(!aiReady?'connect':aiAuthenticated?'cost':'access');return;}busyRef.current=true;setBusy(true);setProgress(0);try{await document.fonts.ready;const out=kind==='image'?await renderPng(design):await renderVideo({...design,ratio:'9:16'},setProgress);setFile(out);message(kind==='image'?'이미지가 완성되었습니다. 저장하거나 공유할 수 있습니다.':'6초 사진 영상이 완성되었습니다. 소리 없는 영상입니다.');}catch(e){message(e instanceof Error?e.message:'제작에 실패했습니다.',true);}finally{setBusy(false);busyRef.current=false;}}
 async function generateAI(){if(busyRef.current)return;setDialog('');setBusy(true);busyRef.current=true;message('AI가 제작 중입니다. 이 화면을 열어두세요.');try{const f=new FormData();f.set('prompt',brief);f.set('kind',kind);f.set('ratio',design.ratio);f.set('confirmed','true');if(design.photo){let blob:Blob;if(kind==='video'){const im=(await loadImage(design.photo))!;const c=document.createElement('canvas');c.width=720;c.height=1280;const scale=Math.max(720/im.width,1280/im.height);c.getContext('2d')!.drawImage(im,(720-im.width*scale)/2,(1280-im.height*scale)/2,im.width*scale,im.height*scale);blob=await new Promise<Blob>(res=>c.toBlob(b=>res(b!),'image/png'));}else blob=await(await fetch(design.photo)).blob();f.set('photo',blob,'reference.png');}const r=await fetch('/api/studio',{method:'POST',body:f});const d=await r.json() as {error?:string;image?:string;id:string;token:string;status:string};if(r.status===401){setAiAuthenticated(false);setDialog('access');}if(!r.ok)throw Error(d.error||"생성에 실패했습니다.");if(d.image){setAiMade(true);setDesign(v=>({...v,photo:d.image!}));setSource('photo');setStep(2);message('그림이 완성됐어요. 확인하고 피드에 올려보세요.');setBusy(false);busyRef.current=false;}else setJob({...d,progress:0});}catch(e){message(e instanceof Error?e.message:'생성 요청을 확인하지 못했습니다. 재요청 전 제공 서비스의 사용 내역을 확인해주세요.',true);setBusy(false);busyRef.current=false;}}
 function saveDraft(){try{localStorage.setItem('jini-voice-draft',JSON.stringify({...state.current,job,source,aiMade}));message('이 기기에 초안을 저장했습니다. 다른 기기와 자동 동기화되지 않습니다.');}catch{message('기기 저장 공간이 부족합니다. 완성 파일을 내려받아주세요.',true);}}
 function loadDraft(){try{const raw=localStorage.getItem('jini-voice-draft');if(!raw){message('이 기기에 저장한 초안이 없습니다.');return;}const d=JSON.parse(raw);if(!d.design||typeof d.design.headline!=='string'||!palettes[d.design.theme]||!['1:1','4:5','9:16'].includes(d.design.ratio))throw Error();setDesign({...initial,...d.design});setBrief(d.brief||'');setCaption(d.caption||'');setKind(['video','text'].includes(d.kind)?d.kind:'image');setSource(d.source==='ai'?'ai':'photo');setAiMade(!!d.aiMade);setStep(1);if(d.job?.id&&d.job?.token)setJob({...d.job,status:'paused'});message('기기에 저장한 초안을 불러왔습니다.');}catch{message('저장된 초안을 읽지 못했습니다.',true);}}
 async function download(){if(busyRef.current){message('제작이 끝나면 저장할 수 있어요.');return;}if(kind==='video'&&!file){message('영상을 먼저 만들어주세요.',true);return;}try{const b=file||await renderPng(design);const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download='jini-voice-'+Date.now()+(b.type.includes('mp4')?'.mp4':b.type.includes('webm')?'.webm':'.png');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);message('파일 저장을 요청했습니다. 기기의 다운로드 또는 파일 앱에서 확인해주세요.');}catch(e){message(e instanceof Error?e.message:'저장에 실패했습니다.',true);}}
 const set=(patch:Partial<Design>)=>setDesign(d=>({...d,...patch}));
 async function publish(){if(publishing||busy)return;const intent=literalText?null:creationIntent(caption);if(kind==='text'&&intent){stageGeneration(caption,intent);return;}if(source==='ai'&&kind!=='text'){setStep(1);message('그림이나 영상을 먼저 완성해주세요.',true);return;}setPublishing(true);try{const output=kind==='text'?null:file||(kind==='image'?await renderPng(design):null);if(kind==='video'&&!output)throw Error('영상을 먼저 완성해주세요.');await onPublish(output,caption,aiMade);}catch(e){message(e instanceof Error?e.message:'게시하지 못했어요. 작성 내용은 그대로 있어요.',true);}finally{setPublishing(false);}}
 function stageGeneration(text:string,requestedKind?:string){const target=requestedKind||creationIntent(text)||'image';setKind(target);setBrief(text);setSource('ai');setStep(1);setLiteralText(false);if(caption.trim()===text.trim())setCaption('');message(target==='video'?'영상으로 만들 장면을 준비했어요.':'그림으로 그릴 내용을 준비했어요.');}
 function preview(){const intent=literalText?null:creationIntent(caption);if(kind==='text'&&intent){stageGeneration(caption,intent);setAuthError('');setDialog(!(intent==='video'?videoReady:imageReady)?'connect':aiAuthenticated?'cost':'access');return;}if(source==='ai'&&kind!=='text'){void create();return;}if(kind==='image'&&!design.photo&&!(design.showText&&design.headline.trim())){message('사진을 넣거나 AI로 그릴 장면을 알려주세요.',true);return;}if(kind==='video'&&!file){message('영상을 먼저 완성해주세요.',true);return;}setStep(2);}
 async function connectAI(){if(busyRef.current)return;busyRef.current=true;setAuthError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'unlock',code})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'접근 코드를 확인해주세요.');setAiAuthenticated(true);setCode('');window.dispatchEvent(new Event('voicegram-auth'));setDialog('cost');}catch(e){setAuthError(e instanceof Error?e.message:'연결하지 못했어요.');}finally{busyRef.current=false;}}
 const generationPending=source==='ai'&&kind!=='text';
 const intentHint=kind==='text'&&!literalText?creationIntent(caption):null;
 const canPreview=kind==='text'?!!caption.trim():source==='ai'?!!brief.trim():kind==='video'?!!file:!!design.photo||!!(design.showText&&design.headline.trim());
 return <div className="compose-page">
 <header className="compose-header"><button className="icon-button" onClick={onClose} aria-label="피드로 돌아가기">←</button><h1>{step===1?'새 이야기':'게시 전 확인'}</h1><button className="text-button" onClick={saveDraft}>임시 저장</button></header>
 <div className="compose-steps"><button aria-current={step===1?'step':undefined} onClick={()=>setStep(1)}>1 이야기하기</button><ChevronRight size={16}/><button aria-current={step===2?'step':undefined} disabled={busy||!canPreview} onClick={preview}>2 확인하고 게시</button></div>
 <div className={step===1?'compose-edit':'compose-edit is-hidden'}>
 <div className="compose-intro"><h2>{mode==='voice'?'편하게 말해보세요':'나누고 싶은 이야기를 써보세요'}</h2><p>{mode==='voice'?'“오늘 즐거웠어”도, “고양이 그려줘”도.':'짧은 한 줄부터 상상 속 장면까지.'}</p></div>
 <div className="compose-entry-switch"><button aria-pressed={mode==='voice'} onClick={()=>setMode('voice')}><Mic size={18}/> 말로 만들기</button><button aria-pressed={mode==='text'} onClick={()=>{setMode('text');setTimeout(()=>document.getElementById('story-caption')?.focus(),50);}}><Type size={18}/> 글로 쓰기</button></div><div className={'composer-prompt '+(generationPending?'is-hidden':'')}><span aria-hidden="true">{storyPrompts[promptIndex].emoji}</span><p>{question||storyPrompts[promptIndex].question}</p><button className="icon-button" aria-label="다른 이야깃거리" onClick={()=>{setQuestion('');setPromptIndex(i=>(i+1)%storyPrompts.length);}}><Shuffle size={17}/></button></div><div hidden={mode!=='voice'||generationPending}><Conversation active={active&&mode==='voice'&&!generationPending} design={design} caption={caption} kind={kind==='text'?'image':kind} disabled={busy||publishing} onChange={changes=>{const {caption:c,kind:k,...patch}=changes;if(Object.keys(patch).length)setDesign(d=>({...d,...patch}));if(c!==undefined)setCaption(c);if(k!==undefined)setKind(k);}} onAction={(action,text,requestedKind)=>{if(action==='share'){preview();}else if(action==='create'){if(kind==='text')preview();else void create();}else if(action==='save')saveDraft();else if(action==='generate'){stageGeneration(text,requestedKind);}else{setCaption(text);setLiteralText(false);}}}/></div>
 <div className={'compose-types '+(generationPending?'is-hidden':'')} role="group" aria-label="게시물 종류">{[['text','글',Type],['image','사진 · 그림',ImageIcon],['video','영상',Film]].map(([v,l,Icon])=>{const I=Icon as typeof Type;return <button key={v as string} disabled={busy} aria-pressed={kind===v} onClick={()=>{setKind(v as string);if(v==='text')setSource('photo');}}><I size={18}/> {l as string}</button>;})}</div>
 <div className={generationPending||mode==='voice'&&!caption?'is-hidden':''}><div className="caption-label"><label className="field-label" htmlFor="story-caption">{mode==='voice'?'받아 적은 이야기':'내 이야기'}</label><span>{caption.length}/2,200</span></div><textarea className="story-input" id="story-caption" placeholder={generationPending?'그림과 함께 올릴 글을 적어도 좋아요.':'오늘 있었던 일이나 만들고 싶은 장면을 적어보세요.'} rows={3} maxLength={2200} value={caption} onChange={e=>{setCaption(e.target.value);setLiteralText(false);}}/>{intentHint?<div className="intent-hint"><Sparkles size={19}/><div><strong>{intentHint==='video'?'영상':'그림'}을 만들고 싶으신가요?</strong><p>요청을 알아들었어요. 아래에서 만들 수 있어요.</p></div><button className="text-button" onClick={()=>setLiteralText(true)}>글로만 쓸게요</button></div>:mode==='text'&&<button className="text-button" disabled={!caption.trim()||busy} onClick={()=>{setMode('voice');window.dispatchEvent(new CustomEvent('voicegram-polish',{detail:caption}));}}><Sparkles size={16}/>AI로 글 다듬기</button>}</div>
 {kind!=='text'&&<div className="media-options"><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/>{!generationPending&&<button className="photo-choice" onClick={()=>input.current?.click()} disabled={busy}>{design.photo?<img src={design.photo} alt="첨부한 사진"/>:<ImagePlus size={28}/>}<span>{design.photo?'사진 바꾸기':'내 사진 넣기'}</span></button>}<button className="text-button" onClick={()=>setSource(v=>v==='ai'?'photo':'ai')} disabled={busy}><Sparkles size={16}/>{source==='ai'?'내 사진으로 만들기':'AI로 새 장면 만들기'}</button>
 {source==='ai'&&<div className="generation-request"><div className="generation-heading"><Sparkles size={21}/><strong>{kind==='video'?'AI 영상 만들기':'AI가 그려드릴게요'}</strong></div><label className="field-label" htmlFor="brief">어떤 장면을 만들까요?</label><textarea id="brief" value={brief} onChange={e=>setBrief(e.target.value)} maxLength={2000} rows={3} placeholder="예: 햇살 드는 창가의 예쁜 고양이"/><p className="muted">{aiReady?'내용을 확인한 뒤 생성해요. API 사용료가 발생합니다.':kind==='video'?'AI 영상 연결을 준비 중이에요. 사진 영상은 만들 수 있어요.':'이미지 생성 서비스 연결이 필요해요.'}</p></div>}
 <details className={'simple-options '+(generationPending?'is-hidden':'')}><summary>글씨 · 분위기 더 꾸미기</summary><label><input type="checkbox" checked={design.showText!==false} onChange={e=>set({showText:e.target.checked})}/> 사진에 글씨 넣기</label>{design.showText!==false&&<><label htmlFor="headline">사진 위 제목</label><input id="headline" value={design.headline} onChange={e=>set({headline:e.target.value})} maxLength={60}/><label htmlFor="subtitle">한 줄 설명</label><input id="subtitle" value={design.subtitle} onChange={e=>set({subtitle:e.target.value})} maxLength={80}/></>}
 <div className="compose-types">{[['classic','차분하게'],['fresh','산뜻하게'],['pop','발랄하게']].map(([v,l])=><button key={v} aria-pressed={design.theme===v} onClick={()=>set({theme:v})}>{l}</button>)}</div><button className="text-button" onClick={()=>set({photo:''})}>사진 빼기</button></details>
 {(source!=='ai'&&kind==='video')&&<button className="primary" disabled={busy} onClick={create}>{busy?'만드는 중…':source==='ai'?`AI ${kind==='video'?'영상':'이미지'} 만들기`:'6초 사진 영상 만들기'}</button>}{kind==='video'&&<p className="muted">사진 영상은 소리 없이 움직이는 6초 영상입니다.</p>}{job?.status==='paused'&&<button className="secondary" onClick={()=>{busyRef.current=true;setBusy(true);setJob({...job,status:'queued'});}}>생성 상태 다시 확인</button>}</div>}
 <button className="primary next-button" disabled={busy||!canPreview} onClick={preview}>{busy?'만드는 중…':generationPending?'확인하고 '+(kind==='video'?'영상':'그림')+' 만들기':intentHint?'AI로 '+(intentHint==='video'?'영상':'그림')+' 만들기':'미리보기'} <ChevronRight size={18}/></button><button className="text-button draft-load" onClick={loadDraft}>임시 저장한 이야기 불러오기</button>
 </div>
 <div className={step===2?'compose-review':'compose-review is-hidden'}>
 <div className="review-note"><ShieldCheck size={20}/><p>이 내용으로 보이스그램 피드에 올릴까요?<small>현재는 참여한 테스터들에게 공개됩니다.</small></p></div>
 <div className={'review-media '+(kind==='text'?'is-hidden':'')}><canvas ref={canvas} style={{display:videoUrl?'none':'block'}} aria-label="게시물 이미지 미리보기"/>{videoUrl&&<video src={videoUrl} controls playsInline/>}</div>
 <label className="field-label" htmlFor="caption">게시글</label><textarea id="caption" value={caption} onChange={e=>setCaption(e.target.value)} rows={5} maxLength={2200}/><div className="emoji-tools">{['✨','💜','🌿','🥰','🎉','🌊','🐾','☕'].map(e=><button key={e} disabled={caption.length+e.length>2200} onClick={()=>setCaption(v=>v+e)} aria-label={e+' 넣기'}>{e}</button>)}</div>
 <button className="primary next-button" onClick={publish} disabled={publishing||busy||(!caption.trim()&&kind==='text')||(!file&&kind==='video')}>{publishing?'올리는 중…':'피드에 게시하기'} <ArrowUpRight size={18}/></button><button className="secondary" onClick={()=>setStep(1)}>돌아가서 수정</button><button className="text-button draft-load" onClick={download} disabled={kind==='text'||busy}>파일로도 저장하기</button>
 </div>
 {busy&&<div className="creation-progress" role="status"><Sparkles size={23}/><span>{source==='ai'?'장면을 만들고 있어요. 잠시만 기다려주세요.':`만드는 중… ${progress}%`}</span></div>}
 {notice&&<p className={'compose-notice '+(error?'error':'')} role={error?'alert':'status'}>{notice}</p>}
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v)setDialog('');}}><DialogContent className="social-dialog creation-dialog"><DialogTitle>{dialog==='cost'?'그림·영상 생성 확인':dialog==='access'?'AI 생성 연결':'연결 안내'}</DialogTitle><DialogDescription>{dialog==='cost'?'생성 요청과 사진이 외부 AI 서비스로 전송되고 API 사용료가 발생합니다.':'이미지와 영상은 연결된 서비스에서 생성합니다.'}</DialogDescription>{dialog==='access'?<><p>이미지 생성은 테스트 접근 코드로 연결한 뒤 이용할 수 있어요.</p><input type="password" autoComplete="off" aria-label="AI 생성 접근 코드" value={code} onChange={e=>setCode(e.target.value)}/><button className="primary" onClick={connectAI} disabled={!code}>연결하고 계속</button>{authError&&<p role="alert">{authError}</p>}</>:dialog==='cost'?<><p>{brief}</p><button className="primary" onClick={generateAI}>비용 발생을 확인하고 생성</button><button className="secondary" onClick={()=>setDialog('')}>취소</button></>:<><p>{aiReady?'AI 서비스가 연결되어 있습니다.':'이 생성 서비스는 아직 연결되지 않았어요. 내 사진이나 글로 이야기를 먼저 나눌 수 있어요.'}</p><button className="primary" onClick={()=>setDialog('')}>돌아가기</button></>}</DialogContent></Dialog>
 </div>;
}
