export type Design = {headline:string; subtitle:string; brand:string; theme:string; ratio:string; fontSize:number; photo:string};
export const palettes:Record<string,{bg:string;fg:string;accent:string;muted:string}> = {fresh:{bg:'#dcebbd',fg:'#183f35',accent:'#345d45',muted:'#46613c'},classic:{bg:'#183f35',fg:'#f3f2e8',accent:'#d8f28b',muted:'#b6cbc0'},pop:{bg:'#ffd953',fg:'#222b26',accent:'#ec562f',muted:'#514b25'}};
export function loadImage(src:string):Promise<HTMLImageElement|null>{return new Promise((resolve,reject)=>{if(!src)return resolve(null);const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('사진을 읽지 못했습니다. JPG 또는 PNG 사진을 다시 넣어주세요.'));im.src=src;});}
function wrap(ctx:CanvasRenderingContext2D,text:string,max:number){const lines:string[]=[];let line='';for(const c of text){if(c==='\n'||(ctx.measureText(line+c).width>max&&line)){lines.push(line);line=c==='\n'?'':c;}else line+=c;}if(line)lines.push(line);return lines;}
export function paint(canvas:HTMLCanvasElement,d:Design,img:HTMLImageElement|null,t=0){const w=1080,h=d.ratio==='9:16'?1920:d.ratio==='4:5'?1350:1080;canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d')!;const p=palettes[d.theme]||palettes.classic;ctx.fillStyle=p.bg;ctx.fillRect(0,0,w,h);
 if(img){const scale=Math.max(w/img.width,h/img.height)*(1+t*.045);ctx.drawImage(img,(w-img.width*scale)/2,(h-img.height*scale)/2,img.width*scale,img.height*scale);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,.13)');g.addColorStop(.3,'rgba(0,0,0,.10)');g.addColorStop(1,'rgba(0,0,0,.88)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}
 const fg=img?'#ffffff':p.fg;ctx.fillStyle=fg;ctx.font='500 34px system-ui, sans-serif';ctx.fillText(d.brand||'YOUR BRAND',74,104);ctx.fillStyle=img?'#d8f28b':p.accent;ctx.fillRect(74,h*.35,62,8);
 let fs=d.fontSize;let lines:string[]=[];do{ctx.font=`750 ${fs}px system-ui, sans-serif`;lines=wrap(ctx,d.headline||'당신의 이야기를\n들려주세요',910);if(lines.length*fs*1.22<h*.43||fs<=40)break;fs-=4;}while(true);ctx.fillStyle=fg;let y=h-300-(lines.length-1)*fs*1.22;lines.forEach(line=>{ctx.fillText(line,74,y);y+=fs*1.22;});ctx.font='400 36px system-ui, sans-serif';ctx.fillStyle=img?'#e2e6e0':p.muted;wrap(ctx,d.subtitle,910).slice(0,3).forEach((line,i)=>ctx.fillText(line,74,h-233+i*43));ctx.strokeStyle=img?'#ffffff60':p.fg+'50';ctx.beginPath();ctx.moveTo(74,h-110);ctx.lineTo(w-74,h-110);ctx.stroke();ctx.font='500 24px system-ui, sans-serif';ctx.fillStyle=fg;ctx.fillText('함께 나누고 싶은 순간',74,h-62);}
export async function renderPng(d:Design){const canvas=document.createElement('canvas');paint(canvas,d,await loadImage(d.photo));return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('저장에 실패했습니다.')),'image/png'));}
export async function renderVideo(d:Design,onProgress:(n:number)=>void){if(typeof MediaRecorder==='undefined')throw Error('이 브라우저는 영상 저장을 지원하지 않습니다. 다른 브라우저에서 이용하거나 이미지로 저장해주세요.');const c=document.createElement('canvas');const img=await loadImage(d.photo);paint(c,d,img);if(!c.captureStream)throw Error('이 브라우저는 영상 저장을 지원하지 않습니다.');const mime=['video/mp4','video/webm;codecs=vp9','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)throw Error('지원하는 영상 형식이 없습니다.');const stream=c.captureStream(24);const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:5000000});return new Promise<Blob>((resolve,reject)=>{const chunks:BlobPart[]=[];let raf=0;const finish=()=>{cancelAnimationFrame(raf);stream.getTracks().forEach(t=>t.stop());document.removeEventListener('visibilitychange',visibility);};const visibility=()=>{if(document.hidden&&rec.state==='recording'){finish();rec.stop();reject(Error('영상 제작 중에는 이 화면을 열어두세요. 다시 시도해주세요.'));}};document.addEventListener('visibilitychange',visibility);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onerror=()=>{finish();reject(Error('영상 제작에 실패했습니다.'));};rec.onstop=()=>{finish();resolve(new Blob(chunks,{type:mime.split(';')[0]}));};rec.start();const start=performance.now();const tick=(now:number)=>{const t=Math.min((now-start)/6000,1);paint(c,d,img,t);onProgress(Math.round(t*100));if(t>=1)rec.stop();else raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);});}
